from __future__ import annotations

from . import rules
from .data import LocationInfo as Info
from .data import LocationType as Type


# List every extra locations (optional depending on options)
EXTRA_LOCATIONS: dict[str, Info] = {
    # ///////////////////////// SHINY SPOTS /////////////////////////
    # ----- Aliahan Overworld -----
    # 001 002 003 004 005 006 007 008 009 010 141
    "[Aliahan Overworld] Shiny Spot near Aliahan: Item 1": Info(1123, type=Type.SHINY), #SHINE_SEARCH_FG000_1
    "[Aliahan Overworld] Shiny Spot near Aliahan: Item 2": Info(1124, type=Type.SHINY_MAX), #SHINE_SEARCH_FG000_2
    "[Aliahan Overworld] Shiny Spot near Aliahan: Item 3": Info(1125, type=Type.SHINY_MAX), #SHINE_SEARCH_FG000_3
    "[Aliahan Overworld] Shiny Spot south-west of Aliahan: Item 1": Info(1126, type=Type.SHINY), #SHINE_SEARCH_FG114_1
    "[Aliahan Overworld] Shiny Spot south-west of Aliahan: Item 2": Info(1127, type=Type.SHINY_MAX), #SHINE_SEARCH_FG114_2
    "[Aliahan Overworld] Shiny Spot south of Shrine of the Plains: Item 1": Info(1128, type=Type.SHINY), #SHINE_SEARCH_FG001_1
    "[Aliahan Overworld] Shiny Spot south of Shrine of the Plains: Item 2": Info(1129, type=Type.SHINY_MAX), #SHINE_SEARCH_FG001_2
    "[Aliahan Overworld] Shiny Spot south of Shrine of the Plains: Item 3": Info(1130, type=Type.SHINY_MAX), #SHINE_SEARCH_FG001_3
    "[Aliahan Overworld] Shiny Spot north of Promontory Passage: Item 1": Info(1131, type=Type.SHINY), #SHINE_SEARCH_FG120_1
    "[Aliahan Overworld] Shiny Spot north of Promontory Passage: Item 2": Info(1132, type=Type.SHINY_MAX), #SHINE_SEARCH_FG120_2
    "[Aliahan Overworld] Shiny Spot north of Promontory Passage: Item 3": Info(1133, type=Type.SHINY_MAX), #SHINE_SEARCH_FG120_3
    "[Aliahan Overworld] Shiny Spot north-west of Promontory Passage: Item 1": Info(1134, type=Type.SHINY), #SHINE_SEARCH_FG115_1
    "[Aliahan Overworld] Shiny Spot north-west of Promontory Passage: Item 2": Info(1135, type=Type.SHINY_MAX), #SHINE_SEARCH_FG115_2
    "[Aliahan Overworld] Shiny Spot north-west of Promontory Passage: Item 3": Info(1136, type=Type.SHINY_MAX), #SHINE_SEARCH_FG115_3
    "[Aliahan Overworld] Shiny Spot on the west coast of the mountain west of Aliahan: Item 1": Info(1137, type=Type.SHINY), #SHINE_SEARCH_FG116_1
    "[Aliahan Overworld] Shiny Spot on the west coast of the mountain west of Aliahan: Item 2": Info(1138, type=Type.SHINY_MAX), #SHINE_SEARCH_FG116_2
    "[Aliahan Overworld] Shiny Spot on the west coast of the mountain west of Aliahan: Item 3": Info(1139, type=Type.SHINY_MAX), #SHINE_SEARCH_FG116_3
    "[Aliahan Overworld] Shiny Spot south-west of Reeve: Item 1": Info(1140, type=Type.SHINY), #SHINE_SEARCH_FG117_1
    "[Aliahan Overworld] Shiny Spot south-west of Reeve: Item 2": Info(1141, type=Type.SHINY_MAX), #SHINE_SEARCH_FG117_2
    "[Aliahan Overworld] Shiny Spot south-west of Reeve: Item 3": Info(1142, type=Type.SHINY_MAX), #SHINE_SEARCH_FG117_3
    "[Aliahan Overworld] Shiny Spot east of Reeve: Item 1": Info(1143, type=Type.SHINY), #SHINE_SEARCH_FG118_1
    "[Aliahan Overworld] Shiny Spot east of Reeve: Item 2": Info(1144, type=Type.SHINY_MAX), #SHINE_SEARCH_FG118_2
    "[Aliahan Overworld] Shiny Spot near the river north-west of Little Shrine: Item 1": Info(1145, type=Type.SHINY), #SHINE_SEARCH_FG003_1
    "[Aliahan Overworld] Shiny Spot near the river north-west of Little Shrine: Item 2": Info(1146, type=Type.SHINY_MAX), #SHINE_SEARCH_FG003_2
    "[Aliahan Overworld] Shiny Spot near the river north-west of Little Shrine: Item 3": Info(1147, type=Type.SHINY_MAX), #SHINE_SEARCH_FG003_3
    "[Aliahan Overworld] Shiny Spot near Little Shrine: Item 1": Info(1148, type=Type.SHINY), #SHINE_SEARCH_FG119_1
    "[Aliahan Overworld] Shiny Spot near Little Shrine: Item 2": Info(1149, type=Type.SHINY_MAX), #SHINE_SEARCH_FG119_2
    "[Aliahan Overworld] Shiny Spot on a small coast north of Path of Promise: Item 1": Info(1150, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG002_1
    "[Aliahan Overworld] Shiny Spot on a small coast north of Path of Promise: Item 2": Info(1151, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG002_2
    "[Aliahan Overworld] Shiny Spot on a small coast north of Path of Promise: Item 3": Info(1152, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG002_3
    # ----- Northwest Overworld -----
    # 011 066 012 013 214 018 019 014 017 020 021 125 022 016 015 212 023 024 211 231 025 213 129(4)
    "[Northwest Overworld] Shiny Spot north of Romarian Road: Item 1": Info(1153, type=Type.SHINY), #SHINE_SEARCH_FG004_1
    "[Northwest Overworld] Shiny Spot north of Romarian Road: Item 2": Info(1154, type=Type.SHINY_MAX), #SHINE_SEARCH_FG004_2
    "[Northwest Overworld] Shiny Spot on the small island south of Shrine of Promise: Item 1": Info(1155, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG177_1
    "[Northwest Overworld] Shiny Spot on the small island south of Shrine of Promise: Item 2": Info(1156, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG177_2
    "[Northwest Overworld] Shiny Spot on the small island south of Shrine of Promise: Item 3": Info(1157, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG177_3
    "[Northwest Overworld] Shiny Spot north-east of Romarian Road: Item 1": Info(1158, type=Type.SHINY), #SHINE_SEARCH_FG122_1
    "[Northwest Overworld] Shiny Spot north-east of Romarian Road: Item 2": Info(1159, type=Type.SHINY_MAX), #SHINE_SEARCH_FG122_2
    "[Northwest Overworld] Shiny Spot north-east of Romarian Road: Item 3": Info(1160, type=Type.SHINY_MAX), #SHINE_SEARCH_FG122_3
    "[Northwest Overworld] Shiny Spot south of Khoryv: Item 1": Info(1161, type=Type.SHINY), #SHINE_SEARCH_FG121_1
    "[Northwest Overworld] Shiny Spot south of Khoryv: Item 2": Info(1162, type=Type.SHINY_MAX), #SHINE_SEARCH_FG121_2
    "[Northwest Overworld] Shiny Spot south of Khoryv: Item 3": Info(1163, type=Type.SHINY_MAX), #SHINE_SEARCH_FG121_3
    "[Northwest Overworld] Shiny Spot in the mountain south-east of Khoryv: Item 1": Info(1164, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG016_1
    "[Northwest Overworld] Shiny Spot in the mountain south-east of Khoryv: Item 2": Info(1165, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG016_2
    "[Northwest Overworld] Shiny Spot in the mountain south-east of Khoryv: Item 3": Info(1166, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG016_3
    "[Northwest Overworld] Shiny Spot east of Khoryv: Item 1": Info(1167, type=Type.SHINY), #SHINE_SEARCH_FG081_1
    "[Northwest Overworld] Shiny Spot east of Khoryv: Item 2": Info(1168, type=Type.SHINY_MAX), #SHINE_SEARCH_FG081_2
    "[Northwest Overworld] Shiny Spot east of Khoryv: Item 3": Info(1169, type=Type.SHINY_MAX), #SHINE_SEARCH_FG081_3
    "[Northwest Overworld] Shiny Spot on the top edge coast of the snowy mountain north-east of Khoryv: Item 1": Info(1170, type=Type.SHINY), #SHINE_SEARCH_FG015_1
    "[Northwest Overworld] Shiny Spot on the top edge coast of the snowy mountain north-east of Khoryv: Item 2": Info(1171, type=Type.SHINY_MAX), #SHINE_SEARCH_FG015_2
    "[Northwest Overworld] Shiny Spot on the top edge coast of the snowy mountain north-east of Khoryv: Item 3": Info(1172, type=Type.SHINY_MAX), #SHINE_SEARCH_FG015_3
    "[Northwest Overworld] Shiny Spot north of Khoryv: Item 1": Info(1173, type=Type.SHINY), #SHINE_SEARCH_FG123_1
    "[Northwest Overworld] Shiny Spot north of Khoryv: Item 2": Info(1174, type=Type.SHINY_MAX), #SHINE_SEARCH_FG123_2
    "[Northwest Overworld] Shiny Spot north of Khoryv: Item 3": Info(1175, type=Type.SHINY_MAX), #SHINE_SEARCH_FG123_3
    "[Northwest Overworld] Shiny Spot near the coast north of Khoryv: Item 1": Info(1176, type=Type.SHINY), #SHINE_SEARCH_FG128_1
    "[Northwest Overworld] Shiny Spot near the coast north of Khoryv: Item 2": Info(1177, type=Type.SHINY_MAX), #SHINE_SEARCH_FG128_2
    "[Northwest Overworld] Shiny Spot on the coast west of Norvik: Item 1": Info(1178, type=Type.SHINY), #SHINE_SEARCH_FG005_1
    "[Northwest Overworld] Shiny Spot on the coast west of Norvik: Item 2": Info(1179, type=Type.SHINY_MAX), #SHINE_SEARCH_FG005_2
    "[Northwest Overworld] Shiny Spot on the coast west of Norvik: Item 3": Info(1180, type=Type.SHINY_MAX), #SHINE_SEARCH_FG005_3
    "[Northwest Overworld] Shiny Spot east of Faerie Village: Item 1": Info(1181, type=Type.SHINY), #SHINE_SEARCH_FG129_1
    "[Northwest Overworld] Shiny Spot east of Faerie Village: Item 2": Info(1182, type=Type.SHINY_MAX), #SHINE_SEARCH_FG129_2
    "[Northwest Overworld] Shiny Spot on a small coast north-east of Faerie Village: Item 1": Info(1183, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG006_1
    "[Northwest Overworld] Shiny Spot on a small coast north-east of Faerie Village: Item 2": Info(1184, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG006_2
    "[Northwest Overworld] Shiny Spot on a small coast north-east of Faerie Village: Item 3": Info(1185, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG006_3
    "[Northwest Overworld] Shiny Spot near Underground Lake: Item 1": Info(1186, type=Type.SHINY), #SHINE_SEARCH_FG125_1
    "[Northwest Overworld] Shiny Spot near Underground Lake: Item 2": Info(1187, type=Type.SHINY_MAX), #SHINE_SEARCH_FG125_2
    "[Northwest Overworld] Shiny Spot on the coast west of Khoryv: Item 1": Info(1188, type=Type.SHINY), #SHINE_SEARCH_FG124_1
    "[Northwest Overworld] Shiny Spot on the coast west of Khoryv: Item 2": Info(1189, type=Type.SHINY_MAX), #SHINE_SEARCH_FG124_2
    "[Northwest Overworld] Shiny Spot on the coast west of Khoryv: Item 3": Info(1190, type=Type.SHINY_MAX), #SHINE_SEARCH_FG124_3
    "[Northwest Overworld] Shiny Spot south-west of Khoryv: Item 1": Info(1191, type=Type.SHINY), #SHINE_SEARCH_FG007_1
    "[Northwest Overworld] Shiny Spot south-west of Khoryv: Item 2": Info(1192, type=Type.SHINY_MAX), #SHINE_SEARCH_FG007_2
    "[Northwest Overworld] Shiny Spot south-west of Khoryv: Item 3": Info(1193, type=Type.SHINY_MAX), #SHINE_SEARCH_FG007_3
    "[Northwest Overworld] Shiny Spot in the mountain north of Skyfell Tower: Item 1": Info(1194, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG008_1
    "[Northwest Overworld] Shiny Spot in the mountain north of Skyfell Tower: Item 2": Info(1195, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG008_2
    "[Northwest Overworld] Shiny Spot in the mountain north of Skyfell Tower: Item 3": Info(1196, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG008_3
    "[Northwest Overworld] Shiny Spot north of Skyfell Tower: Item 1": Info(1197, type=Type.SHINY), #SHINE_SEARCH_FG126_1
    "[Northwest Overworld] Shiny Spot north of Skyfell Tower: Item 2": Info(1198, type=Type.SHINY_MAX), #SHINE_SEARCH_FG126_2
    "[Northwest Overworld] Shiny Spot near Skyfell Tower: Item 1": Info(1199, type=Type.SHINY), #SHINE_SEARCH_FG127_1
    "[Northwest Overworld] Shiny Spot near Skyfell Tower: Item 2": Info(1200, type=Type.SHINY_MAX), #SHINE_SEARCH_FG127_2
    "[Northwest Overworld] Shiny Spot near Skyfell Tower: Item 3": Info(1201, type=Type.SHINY_MAX), #SHINE_SEARCH_FG127_3
    "[Northwest Overworld] Shiny Spot in the mountain east of Skyfell Tower: Item 1": Info(1202, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG009_1
    "[Northwest Overworld] Shiny Spot in the mountain east of Skyfell Tower: Item 2": Info(1203, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG009_2
    "[Northwest Overworld] Shiny Spot in the mountain east of Skyfell Tower: Item 3": Info(1204, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG009_3
    "[Northwest Overworld] Shiny Spot on the small coast south-east of Skyfell Tower: Item 1": Info(1205, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG010_1
    "[Northwest Overworld] Shiny Spot on the small coast south-east of Skyfell Tower: Item 2": Info(1206, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG010_2
    "[Northwest Overworld] Shiny Spot on the small coast south-east of Skyfell Tower: Item 3": Info(1207, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG010_3
    "[Northwest Overworld] Shiny Spot on the bottom edge coast south of Skyfell Tower: Item 1": Info(1208, type=Type.SHINY), #SHINE_SEARCH_FG011_1
    "[Northwest Overworld] Shiny Spot on the bottom edge coast south of Skyfell Tower: Item 2": Info(1209, type=Type.SHINY_MAX), #SHINE_SEARCH_FG011_2
    "[Northwest Overworld] Shiny Spot on the bottom edge coast south of Skyfell Tower: Item 3": Info(1210, type=Type.SHINY_MAX), #SHINE_SEARCH_FG011_3
    "[Northwest Overworld] Shiny Spot in the mountain north of Edina Castle: Item 1": Info(1211, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG013_1
    "[Northwest Overworld] Shiny Spot in the mountain north of Edina Castle: Item 2": Info(1212, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG013_2
    "[Northwest Overworld] Shiny Spot 1 on the island west of Edina Castle: Item 1": Info(1213, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG164_1
    "[Northwest Overworld] Shiny Spot 1 on the island west of Edina Castle: Item 2": Info(1214, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG164_2
    "[Northwest Overworld] Shiny Spot 2 on the island west of Edina Castle: Item 1": Info(1215, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG163_1
    "[Northwest Overworld] Shiny Spot 3 on the island west of Edina Castle: Item 1": Info(1216, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG162_1
    "[Northwest Overworld] Shiny Spot 3 on the island west of Edina Castle: Item 2": Info(1217, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG162_2
    "[Northwest Overworld] Shiny Spot 4 on the island west of Edina Castle: Item 1": Info(1218, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG014_1
    # ----- Great Desert Overworld -----
    # 026 027 028 029 069(2) 030 031 032 216 033 039 038 037(3) 035 034 208 036
    "[Great Desert Overworld] Shiny Spot south of the bridge between Asham and Romaria: Item 1": Info(1219, type=Type.SHINY), #SHINE_SEARCH_FG130_1
    "[Great Desert Overworld] Shiny Spot south of the bridge between Asham and Romaria: Item 2": Info(1220, type=Type.SHINY_MAX), #SHINE_SEARCH_FG130_2
    "[Great Desert Overworld] Shiny Spot south of the bridge between Asham and Romaria: Item 3": Info(1221, type=Type.SHINY_MAX), #SHINE_SEARCH_FG130_3
    "[Great Desert Overworld] Shiny Spot near the mountain north of Asham: Item 1": Info(1222, type=Type.SHINY), #SHINE_SEARCH_FG019_1
    "[Great Desert Overworld] Shiny Spot near the mountain north of Asham: Item 2": Info(1223, type=Type.SHINY_MAX), #SHINE_SEARCH_FG019_2
    "[Great Desert Overworld] Shiny Spot near the mountain north of Asham: Item 3": Info(1224, type=Type.SHINY_MAX), #SHINE_SEARCH_FG019_3
    "[Great Desert Overworld] Shiny Spot north-west of Asham: Item 1": Info(1225, type=Type.SHINY), #SHINE_SEARCH_FG131_1
    "[Great Desert Overworld] Shiny Spot north-west of Asham: Item 2": Info(1226, type=Type.SHINY_MAX), #SHINE_SEARCH_FG131_2
    "[Great Desert Overworld] Shiny Spot north-west of Asham: Item 3": Info(1227, type=Type.SHINY_MAX), #SHINE_SEARCH_FG131_3
    "[Great Desert Overworld] Shiny Spot near Asham: Item 1": Info(1228, type=Type.SHINY), #SHINE_SEARCH_FG134_1
    "[Great Desert Overworld] Shiny Spot near Asham: Item 2": Info(1229, type=Type.SHINY_MAX), #SHINE_SEARCH_FG134_2
    "[Great Desert Overworld] Shiny Spot 1 on the coast behind the mountain west of Asham: Item 1": Info(1230, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG018_1
    "[Great Desert Overworld] Shiny Spot 1 on the coast behind the mountain west of Asham: Item 2": Info(1231, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG018_2
    "[Great Desert Overworld] Shiny Spot 1 on the coast behind the mountain west of Asham: Item 3": Info(1232, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG018_3
    "[Great Desert Overworld] Shiny Spot 2 on the coast behind the mountain west of Asham: Item 1": Info(1233, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG176_1
    "[Great Desert Overworld] Shiny Spot 2 on the coast behind the mountain west of Asham: Item 2": Info(1234, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG176_2
    "[Great Desert Overworld] Shiny Spot south of Asham: Item 1": Info(1235, type=Type.SHINY), #SHINE_SEARCH_FG132_1
    "[Great Desert Overworld] Shiny Spot south of Asham: Item 2": Info(1236, type=Type.SHINY_MAX), #SHINE_SEARCH_FG132_2
    "[Great Desert Overworld] Shiny Spot south of Asham: Item 3": Info(1237, type=Type.SHINY_MAX), #SHINE_SEARCH_FG132_3
    "[Great Desert Overworld] Shiny Spot south of the forest south of Asham: Item 1": Info(1238, type=Type.SHINY), #SHINE_SEARCH_FG133_1
    "[Great Desert Overworld] Shiny Spot south of the forest south of Asham: Item 2": Info(1239, type=Type.SHINY_MAX), #SHINE_SEARCH_FG133_2
    "[Great Desert Overworld] Shiny Spot south of the forest south of Asham: Item 3": Info(1240, type=Type.SHINY_MAX), #SHINE_SEARCH_FG133_3
    "[Great Desert Overworld] Shiny Spot west of the forest south of Asham: Item 1": Info(1241, type=Type.SHINY), #SHINE_SEARCH_FG021_1
    "[Great Desert Overworld] Shiny Spot west of the forest south of Asham: Item 2": Info(1242, type=Type.SHINY_MAX), #SHINE_SEARCH_FG021_2
    "[Great Desert Overworld] Shiny Spot in the center of the forest south of Asham: Item 1": Info(1243, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG020_1
    "[Great Desert Overworld] Shiny Spot in the center of the forest south of Asham: Item 2": Info(1244, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG020_2
    "[Great Desert Overworld] Shiny Spot in the center of the forest south of Asham: Item 3": Info(1245, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG020_3
    "[Great Desert Overworld] Shiny Spot in the forest on the coast north-east of the Pyramid: Item 1": Info(1246, type=Type.SHINY), #SHINE_SEARCH_FG137_1
    "[Great Desert Overworld] Shiny Spot in the forest on the coast north-east of the Pyramid: Item 2": Info(1247, type=Type.SHINY_MAX), #SHINE_SEARCH_FG137_2
    "[Great Desert Overworld] Shiny Spot in the forest on the coast north-east of the Pyramid: Item 3": Info(1248, type=Type.SHINY_MAX), #SHINE_SEARCH_FG137_3
    "[Great Desert Overworld] Shiny Spot north of the Pyramid: Item 1": Info(1249, type=Type.SHINY), #SHINE_SEARCH_FG138_1
    "[Great Desert Overworld] Shiny Spot north of the Pyramid: Item 2": Info(1250, type=Type.SHINY_MAX), #SHINE_SEARCH_FG138_2
    "[Great Desert Overworld] Shiny Spot north of the Pyramid: Item 3": Info(1251, type=Type.SHINY_MAX), #SHINE_SEARCH_FG138_3
    "[Great Desert Overworld] Shiny Spot north-west of Ibis: Item 1": Info(1252, type=Type.SHINY), #SHINE_SEARCH_FG139_1
    "[Great Desert Overworld] Shiny Spot north-west of Ibis: Item 2": Info(1253, type=Type.SHINY_MAX), #SHINE_SEARCH_FG139_2
    "[Great Desert Overworld] Shiny Spot north-west of Ibis: Item 3": Info(1254, type=Type.SHINY_MAX), #SHINE_SEARCH_FG139_3
    "[Great Desert Overworld] Shiny Spot 1 in the center of the desert north of Ibis: Item 1": Info(1255, type=Type.SHINY), #SHINE_SEARCH_FG142_1
    "[Great Desert Overworld] Shiny Spot 1 in the center of the desert north of Ibis: Item 2": Info(1256, type=Type.SHINY_MAX), #SHINE_SEARCH_FG142_2
    "[Great Desert Overworld] Shiny Spot 1 in the center of the desert north of Ibis: Item 3": Info(1257, type=Type.SHINY_MAX), #SHINE_SEARCH_FG142_3
    "[Great Desert Overworld] Shiny Spot 2 in the center of the desert north of Ibis: Item 1": Info(1258, type=Type.SHINY), #SHINE_SEARCH_FG140_1
    "[Great Desert Overworld] Shiny Spot 2 in the center of the desert north of Ibis: Item 2": Info(1259, type=Type.SHINY_MAX), #SHINE_SEARCH_FG140_2
    "[Great Desert Overworld] Shiny Spot 3 in the center of the desert north of Ibis: Item 1": Info(1260, type=Type.SHINY), #SHINE_SEARCH_FG141_1
    "[Great Desert Overworld] Shiny Spot north-east of Ibis: Item 1": Info(1261, type=Type.SHINY), #SHINE_SEARCH_FG022_1
    "[Great Desert Overworld] Shiny Spot north-east of Ibis: Item 2": Info(1262, type=Type.SHINY_MAX), #SHINE_SEARCH_FG022_2
    "[Great Desert Overworld] Shiny Spot north-east of Ibis: Item 3": Info(1263, type=Type.SHINY_MAX), #SHINE_SEARCH_FG022_3
    "[Great Desert Overworld] Shiny Spot in the rocky area north-east of Ibis: Item 1": Info(1264, type=Type.SHINY), #SHINE_SEARCH_FG136_1
    "[Great Desert Overworld] Shiny Spot in the rocky area north-east of Ibis: Item 2": Info(1265, type=Type.SHINY_MAX), #SHINE_SEARCH_FG136_2
    "[Great Desert Overworld] Shiny Spot in the mountain east of Ibis: Item 1": Info(1266, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG023_1
    "[Great Desert Overworld] Shiny Spot in the mountain east of Ibis: Item 2": Info(1267, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG023_2
    "[Great Desert Overworld] Shiny Spot near Desert Shrine: Item 1": Info(1268, type=Type.SHINY), #SHINE_SEARCH_FG135_1
    "[Great Desert Overworld] Shiny Spot near Desert Shrine: Item 2": Info(1269, type=Type.SHINY_MAX), #SHINE_SEARCH_FG135_2
    "[Great Desert Overworld] Shiny Spot near Desert Shrine: Item 3": Info(1270, type=Type.SHINY_MAX), #SHINE_SEARCH_FG135_3
    # ----- Portoga Overworld -----
    # 040 041 210 042
    "[Portoga Overworld] Shiny Spot in the forest west of the path to Portoga: Item 1": Info(1271, type=Type.SHINY), #SHINE_SEARCH_FG143_1
    "[Portoga Overworld] Shiny Spot in the forest west of the path to Portoga: Item 2": Info(1272, type=Type.SHINY_MAX), #SHINE_SEARCH_FG143_2
    "[Portoga Overworld] Shiny Spot north of Portoga: Item 1": Info(1273, type=Type.SHINY), #SHINE_SEARCH_FG145_1
    "[Portoga Overworld] Shiny Spot north of Portoga: Item 2": Info(1274, type=Type.SHINY_MAX), #SHINE_SEARCH_FG145_2
    "[Portoga Overworld] Shiny Spot north of Portoga: Item 3": Info(1275, type=Type.SHINY_MAX), #SHINE_SEARCH_FG145_3
    "[Portoga Overworld] Shiny Spot in the mountain north-west of Portoga: Item 1": Info(1276, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG012_1
    "[Portoga Overworld] Shiny Spot in the mountain north-west of Portoga: Item 2": Info(1277, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG012_2
    "[Portoga Overworld] Shiny Spot in the mountain north-west of Portoga: Item 3": Info(1278, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG012_3
    "[Portoga Overworld] Shiny Spot west of Portoga: Item 1": Info(1279, type=Type.SHINY), #SHINE_SEARCH_FG144_1
    "[Portoga Overworld] Shiny Spot west of Portoga: Item 2": Info(1280, type=Type.SHINY_MAX), #SHINE_SEARCH_FG144_2
    # ----- Central Overworld -----
    # 045 046 044 043 047 217 048 086 049 050 218 051 089 052 053 054 055 056 057 058 059 219 090 091 092
    # 093 060 061 062 095 232 220 063 097 101 106 107 105 104 103 102 221 110 108 222 117 215 115 116 114 113(2)
    "[Central Overworld] Shiny Spot south-west of Olivia's Promontory: Item 1": Info(1281, type=Type.SHINY), #SHINE_SEARCH_FG033_1
    "[Central Overworld] Shiny Spot south-west of Olivia's Promontory: Item 2": Info(1282, type=Type.SHINY_MAX), #SHINE_SEARCH_FG033_2
    "[Central Overworld] Shiny Spot south-west of Olivia's Promontory: Item 3": Info(1283, type=Type.SHINY_MAX), #SHINE_SEARCH_FG033_3
    "[Central Overworld] Shiny Spot south-east of Olivia's Promontory: Item 1": Info(1284, type=Type.SHINY), #SHINE_SEARCH_FG146_1
    "[Central Overworld] Shiny Spot south-east of Olivia's Promontory: Item 2": Info(1285, type=Type.SHINY_MAX), #SHINE_SEARCH_FG146_2
    "[Central Overworld] Shiny Spot south-east of Olivia's Promontory: Item 3": Info(1286, type=Type.SHINY_MAX), #SHINE_SEARCH_FG146_3
    "[Central Overworld] Shiny Spot north of Nordy's Grotto's right entrance: Item 1": Info(1287, type=Type.SHINY), #SHINE_SEARCH_FG149_1
    "[Central Overworld] Shiny Spot north of Nordy's Grotto's right entrance: Item 2": Info(1288, type=Type.SHINY_MAX), #SHINE_SEARCH_FG149_2
    "[Central Overworld] Shiny Spot north of Nordy's Grotto's right entrance: Item 3": Info(1289, type=Type.SHINY_MAX), #SHINE_SEARCH_FG149_3
    "[Central Overworld] Shiny Spot east of Nordy's Grotto's right entrance: Item 1": Info(1290, type=Type.SHINY), #SHINE_SEARCH_FG034_1
    "[Central Overworld] Shiny Spot east of Nordy's Grotto's right entrance: Item 2": Info(1291, type=Type.SHINY_MAX), #SHINE_SEARCH_FG034_2
    "[Central Overworld] Shiny Spot near the lake south of Nordy's Grotto's right entrance: Item 1": Info(1292, type=Type.SHINY), #SHINE_SEARCH_FG035_1
    "[Central Overworld] Shiny Spot near the lake south of Nordy's Grotto's right entrance: Item 2": Info(1293, type=Type.SHINY_MAX), #SHINE_SEARCH_FG035_2
    "[Central Overworld] Shiny Spot near the lake south of Nordy's Grotto's right entrance: Item 3": Info(1294, type=Type.SHINY_MAX), #SHINE_SEARCH_FG035_3
    "[Central Overworld] Shiny Spot in the mountain north-west of Baharata: Item 1": Info(1295, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG037_1
    "[Central Overworld] Shiny Spot in the mountain north-west of Baharata: Item 2": Info(1296, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG037_2
    "[Central Overworld] Shiny Spot in the mountain north-west of Baharata: Item 3": Info(1297, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG037_3
    "[Central Overworld] Shiny Spot west of the mountain north-west of Baharata: Item 1": Info(1298, type=Type.SHINY), #SHINE_SEARCH_FG147_1
    "[Central Overworld] Shiny Spot west of the mountain north-west of Baharata: Item 2": Info(1299, type=Type.SHINY_MAX), #SHINE_SEARCH_FG147_2
    "[Central Overworld] Shiny Spot on the small coast west of the mountain north-west of Baharata: Item 1": Info(1300, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG036_1
    "[Central Overworld] Shiny Spot on the small coast west of the mountain north-west of Baharata: Item 2": Info(1301, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG036_2
    "[Central Overworld] Shiny Spot on the small coast west of the mountain north-west of Baharata: Item 3": Info(1302, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG036_3
    "[Central Overworld] Shiny Spot in the desert area west of the lake north-west of Baharata: Item 1": Info(1303, type=Type.SHINY), #SHINE_SEARCH_FG148_1
    "[Central Overworld] Shiny Spot in the desert area west of the lake north-west of Baharata: Item 2": Info(1304, type=Type.SHINY_MAX), #SHINE_SEARCH_FG148_2
    "[Central Overworld] Shiny Spot west of Baharata: Item 1": Info(1305, type=Type.SHINY), #SHINE_SEARCH_FG038_1
    "[Central Overworld] Shiny Spot west of Baharata: Item 2": Info(1306, type=Type.SHINY_MAX), #SHINE_SEARCH_FG038_2
    "[Central Overworld] Shiny Spot west of Baharata: Item 3": Info(1307, type=Type.SHINY_MAX), #SHINE_SEARCH_FG038_3
    "[Central Overworld] Shiny Spot in the mountain south-west of Baharata: Item 1": Info(1308, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG039_1
    "[Central Overworld] Shiny Spot in the mountain south-west of Baharata: Item 2": Info(1309, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG039_2
    "[Central Overworld] Shiny Spot south of the mountain south-west of Baharata: Item 1": Info(1310, type=Type.SHINY), #SHINE_SEARCH_FG150_1
    "[Central Overworld] Shiny Spot south of the mountain south-west of Baharata: Item 2": Info(1311, type=Type.SHINY_MAX), #SHINE_SEARCH_FG150_2
    "[Central Overworld] Shiny Spot on the small island south of Baharata: Item 1": Info(1312, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG215_1
    "[Central Overworld] Shiny Spot on the small island south of Baharata: Item 2": Info(1313, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG215_2
    "[Central Overworld] Shiny Spot on the small island south of Baharata: Item 3": Info(1314, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG215_3
    "[Central Overworld] Shiny Spot east of Baharata: Item 1": Info(1315, type=Type.SHINY), #SHINE_SEARCH_FG152_1
    "[Central Overworld] Shiny Spot east of Baharata: Item 2": Info(1316, type=Type.SHINY_MAX), #SHINE_SEARCH_FG152_2
    "[Central Overworld] Shiny Spot east of Baharata: Item 3": Info(1317, type=Type.SHINY_MAX), #SHINE_SEARCH_FG152_3
    "[Central Overworld] Shiny Spot on the bottom edge coast south-east of Baharata: Item 1": Info(1318, type=Type.SHINY), #SHINE_SEARCH_FG151_1
    "[Central Overworld] Shiny Spot on the bottom edge coast south-east of Baharata: Item 2": Info(1319, type=Type.SHINY_MAX), #SHINE_SEARCH_FG151_2
    "[Central Overworld] Shiny Spot on the bottom edge coast south-east of Baharata: Item 3": Info(1320, type=Type.SHINY_MAX), #SHINE_SEARCH_FG151_3
    "[Central Overworld] Shiny Spot on the coast near Jipang to the east of Baharata: Item 1": Info(1321, type=Type.SHINY), #SHINE_SEARCH_FG041_1
    "[Central Overworld] Shiny Spot on the coast near Jipang to the east of Baharata: Item 2": Info(1322, type=Type.SHINY_MAX), #SHINE_SEARCH_FG041_2
    "[Central Overworld] Shiny Spot on the coast near Jipang to the east of Baharata: Item 3": Info(1323, type=Type.SHINY_MAX), #SHINE_SEARCH_FG041_3
    "[Central Overworld] Shiny Spot north-east of Kidnapper's Cave: Item 1": Info(1324, type=Type.SHINY), #SHINE_SEARCH_FG157_1
    "[Central Overworld] Shiny Spot north-east of Kidnapper's Cave: Item 2": Info(1325, type=Type.SHINY_MAX), #SHINE_SEARCH_FG157_2
    "[Central Overworld] Shiny Spot south of Alltrades Abbey: Item 1": Info(1326, type=Type.SHINY), #SHINE_SEARCH_FG160_1
    "[Central Overworld] Shiny Spot south of Alltrades Abbey: Item 2": Info(1327, type=Type.SHINY_MAX), #SHINE_SEARCH_FG160_2
    "[Central Overworld] Shiny Spot south of Alltrades Abbey: Item 3": Info(1328, type=Type.SHINY_MAX), #SHINE_SEARCH_FG160_3
    "[Central Overworld] Shiny Spot north of Alltrades Abbey: Item 1": Info(1329, type=Type.SHINY), #SHINE_SEARCH_FG040_1
    "[Central Overworld] Shiny Spot north of Alltrades Abbey: Item 2": Info(1330, type=Type.SHINY_MAX), #SHINE_SEARCH_FG040_2
    "[Central Overworld] Shiny Spot north of Alltrades Abbey: Item 3": Info(1331, type=Type.SHINY_MAX), #SHINE_SEARCH_FG040_3
    "[Central Overworld] Shiny Spot south-east of Alltrades Abbey: Item 1": Info(1332, type=Type.SHINY), #SHINE_SEARCH_FG158_1
    "[Central Overworld] Shiny Spot south-east of Alltrades Abbey: Item 2": Info(1333, type=Type.SHINY_MAX), #SHINE_SEARCH_FG158_2
    "[Central Overworld] Shiny Spot south-east of Alltrades Abbey: Item 3": Info(1334, type=Type.SHINY_MAX), #SHINE_SEARCH_FG158_3
    "[Central Overworld] Shiny Spot near the coast south-west of Wayfarer's Inn: Item 1": Info(1335, type=Type.SHINY), #SHINE_SEARCH_FG042_1
    "[Central Overworld] Shiny Spot near the coast south-west of Wayfarer's Inn: Item 2": Info(1336, type=Type.SHINY_MAX), #SHINE_SEARCH_FG042_2
    "[Central Overworld] Shiny Spot near the coast south-west of Wayfarer's Inn: Item 3": Info(1337, type=Type.SHINY_MAX), #SHINE_SEARCH_FG042_3
    "[Central Overworld] Shiny Spot on the other side of the lake north-west of Wayfarer's Inn: Item 1": Info(1338, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG043_1
    "[Central Overworld] Shiny Spot on the other side of the lake north-west of Wayfarer's Inn: Item 2": Info(1339, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG043_2
    "[Central Overworld] Shiny Spot on the small island west of Jipang: Item 1": Info(1340, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG169_1
    "[Central Overworld] Shiny Spot on the small island west of Jipang: Item 2": Info(1341, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG169_2
    "[Central Overworld] Shiny Spot on the small island south-west of Jipang: Item 1": Info(1342, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG170_1
    "[Central Overworld] Shiny Spot on the small island south-west of Jipang: Item 2": Info(1343, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG170_2
    "[Central Overworld] Shiny Spot on the small island south-west of Jipang: Item 3": Info(1344, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG170_3
    "[Central Overworld] Shiny Spot on the first small island north of Orochi's Lair: Item 1": Info(1345, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG171_1
    "[Central Overworld] Shiny Spot on the first small island north of Orochi's Lair: Item 2": Info(1346, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG171_2
    "[Central Overworld] Shiny Spot on the first small island north of Orochi's Lair: Item 3": Info(1347, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG171_3
    "[Central Overworld] Shiny Spot on the second small island north of Orochi's Lair: Item 1": Info(1348, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG172_1
    "[Central Overworld] Shiny Spot on the second small island north of Orochi's Lair: Item 2": Info(1349, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG172_2
    "[Central Overworld] Shiny Spot on the second small island north of Orochi's Lair: Item 3": Info(1350, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG172_3
    "[Central Overworld] Shiny Spot near the coast north-east of Wayfarer's Inn: Item 1": Info(1351, type=Type.SHINY), #SHINE_SEARCH_FG044_1
    "[Central Overworld] Shiny Spot near the coast north-east of Wayfarer's Inn: Item 2": Info(1352, type=Type.SHINY_MAX), #SHINE_SEARCH_FG044_2
    "[Central Overworld] Shiny Spot near the coast north-east of Wayfarer's Inn: Item 3": Info(1353, type=Type.SHINY_MAX), #SHINE_SEARCH_FG044_3
    "[Central Overworld] Shiny Spot north of Wayfarer's Inn: Item 1": Info(1354, type=Type.SHINY), #SHINE_SEARCH_FG153_1
    "[Central Overworld] Shiny Spot north of Wayfarer's Inn: Item 2": Info(1355, type=Type.SHINY_MAX), #SHINE_SEARCH_FG153_2
    "[Central Overworld] Shiny Spot north of Wayfarer's Inn: Item 3": Info(1356, type=Type.SHINY_MAX), #SHINE_SEARCH_FG153_3
    "[Central Overworld] Shiny Spot near the lake south-west of Mur: Item 1": Info(1357, type=Type.SHINY), #SHINE_SEARCH_FG154_1
    "[Central Overworld] Shiny Spot near the lake south-west of Mur: Item 2": Info(1358, type=Type.SHINY_MAX), #SHINE_SEARCH_FG154_2
    "[Central Overworld] Shiny Spot near the lake south-west of Mur: Item 3": Info(1359, type=Type.SHINY_MAX), #SHINE_SEARCH_FG154_3
    "[Central Overworld] Shiny Spot on the small coast south of Mur: Item 1": Info(1360, type=Type.SHINY), #SHINE_SEARCH_FG045_1
    "[Central Overworld] Shiny Spot on the small coast south of Mur: Item 2": Info(1361, type=Type.SHINY_MAX), #SHINE_SEARCH_FG045_2
    "[Central Overworld] Shiny Spot on the small coast south of Mur: Item 3": Info(1362, type=Type.SHINY_MAX), #SHINE_SEARCH_FG045_3
    "[Central Overworld] Shiny Spot north-west of Mur: Item 1": Info(1363, type=Type.SHINY), #SHINE_SEARCH_FG155_1
    "[Central Overworld] Shiny Spot north-west of Mur: Item 2": Info(1364, type=Type.SHINY_MAX), #SHINE_SEARCH_FG155_2
    "[Central Overworld] Shiny Spot in the mountain north of Mur: Item 1": Info(1365, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG046_1
    "[Central Overworld] Shiny Spot in the mountain north of Mur: Item 2": Info(1366, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG046_2
    "[Central Overworld] Shiny Spot near the top edge coast north-west of Mur: Item 1": Info(1367, type=Type.SHINY), #SHINE_SEARCH_FG156_1
    "[Central Overworld] Shiny Spot near the top edge coast north-west of Mur: Item 2": Info(1368, type=Type.SHINY_MAX), #SHINE_SEARCH_FG156_2
    "[Central Overworld] Shiny Spot near the top edge coast north-west of Mur: Item 3": Info(1369, type=Type.SHINY_MAX), #SHINE_SEARCH_FG156_3
    "[Central Overworld] Shiny Spot on the other side of the river west of Mur: Item 1": Info(1370, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG047_1
    "[Central Overworld] Shiny Spot on the other side of the river west of Mur: Item 2": Info(1371, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG047_2
    "[Central Overworld] Shiny Spot on the other side of the river west of Mur: Item 3": Info(1372, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG047_3
    "[Central Overworld] Shiny Spot on the other side of the river north-west of Mur: Item 1": Info(1373, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG218_1
    "[Central Overworld] Shiny Spot on the other side of the river north-west of Mur: Item 2": Info(1374, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG218_2
    "[Central Overworld] Shiny Spot on the other side of the river north-west of Mur: Item 3": Info(1375, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG218_3
    "[Central Overworld] Shiny Spot 1 south of Shrine of the Dwarf: Item 1": Info(1376, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG050_1
    "[Central Overworld] Shiny Spot 1 south of Shrine of the Dwarf: Item 2": Info(1377, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG050_2
    "[Central Overworld] Shiny Spot 1 south of Shrine of the Dwarf: Item 3": Info(1378, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG050_3
    "[Central Overworld] Shiny Spot 2 south of Shrine of the Dwarf: Item 1": Info(1379, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG222_1
    "[Central Overworld] Shiny Spot 2 south of Shrine of the Dwarf: Item 2": Info(1380, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG222_2
    "[Central Overworld] Shiny Spot 2 south of Shrine of the Dwarf: Item 3": Info(1381, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG222_3
    "[Central Overworld] Shiny Spot 3 south of Shrine of the Dwarf: Item 1": Info(1382, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG221_1
    "[Central Overworld] Shiny Spot 3 south of Shrine of the Dwarf: Item 2": Info(1383, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG221_2
    "[Central Overworld] Shiny Spot 1 east of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1384, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG220_1
    "[Central Overworld] Shiny Spot 1 east of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1385, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG220_2
    "[Central Overworld] Shiny Spot 2 east of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1386, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG219_1
    "[Central Overworld] Shiny Spot 2 east of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1387, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG219_2
    "[Central Overworld] Shiny Spot 2 east of the center of the forest south of Shrine of the Dwarf: Item 3": Info(1388, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG219_3
    "[Central Overworld] Shiny Spot south-east of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1389, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG048_1
    "[Central Overworld] Shiny Spot south-east of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1390, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG048_2
    "[Central Overworld] Shiny Spot south of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1391, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG049_1
    "[Central Overworld] Shiny Spot south of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1392, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG049_2
    "[Central Overworld] Shiny Spot south of the center of the forest south of Shrine of the Dwarf: Item 3": Info(1393, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG049_3
    "[Central Overworld] Shiny Spot on the small coast south-west of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1394, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG224_1
    "[Central Overworld] Shiny Spot on the small coast south-west of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1395, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG224_2
    "[Central Overworld] Shiny Spot 1 north-west of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1396, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG223_1
    "[Central Overworld] Shiny Spot 1 north-west of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1397, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG223_2
    "[Central Overworld] Shiny Spot 2 north-west of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1398, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG051_1
    "[Central Overworld] Shiny Spot 2 north-west of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1399, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG051_2
    "[Central Overworld] Shiny Spot 2 north-west of the center of the forest south of Shrine of the Dwarf: Item 3": Info(1400, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG051_3
    "[Central Overworld] Shiny Spot north-west of Olivia's Promontory: Item 1": Info(1401, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG052_1
    "[Central Overworld] Shiny Spot north-west of Olivia's Promontory: Item 2": Info(1402, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG052_2
    "[Central Overworld] Shiny Spot north-west of Olivia's Promontory: Item 3": Info(1403, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG052_3
    "[Central Overworld] Shiny Spot in the mountain north of Olivia's Promontory: Item 1": Info(1404, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG053_1
    "[Central Overworld] Shiny Spot in the mountain north of Olivia's Promontory: Item 2": Info(1405, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG053_2
    "[Central Overworld] Shiny Spot south-west of Castle of the Dragon Queen: Item 1": Info(1406, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG213_1
    "[Central Overworld] Shiny Spot south-west of Castle of the Dragon Queen: Item 2": Info(1407, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG213_2
    "[Central Overworld] Shiny Spot north-west of Castle of the Dragon Queen: Item 1": Info(1408, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG054_1
    "[Central Overworld] Shiny Spot north-west of Castle of the Dragon Queen: Item 2": Info(1409, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG054_2
    "[Central Overworld] Shiny Spot north-east of Castle of the Dragon Queen: Item 1": Info(1410, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG055_1
    "[Central Overworld] Shiny Spot north-east of Castle of the Dragon Queen: Item 2": Info(1411, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG055_2
    "[Central Overworld] Shiny Spot north-east of Castle of the Dragon Queen: Item 3": Info(1412, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG055_3
    "[Central Overworld] Shiny Spot 1 on the small coast north of Castle of the Dragon Queen: Item 1": Info(1413, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG214_1
    "[Central Overworld] Shiny Spot 1 on the small coast north of Castle of the Dragon Queen: Item 2": Info(1414, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG214_2
    "[Central Overworld] Shiny Spot 1 on the small coast north of Castle of the Dragon Queen: Item 3": Info(1415, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG214_3
    "[Central Overworld] Shiny Spot 2 on the small coast north of Castle of the Dragon Queen: Item 1": Info(1416, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG056_1
    "[Central Overworld] Shiny Spot 2 on the small coast north of Castle of the Dragon Queen: Item 2": Info(1417, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG056_2
    "[Central Overworld] Shiny Spot 2 on the small coast north of Castle of the Dragon Queen: Item 3": Info(1418, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG056_3
    # ----- Eastern Overworld -----
    # 173 174 177 176 166(3) 165 227 162 159 160 161 182 183 184 185 186 187 188 189 191 192 194 193 195(3) 158
    # 226 157 155 225 154 153 152 151(3) 150 223 148 146(2) 147
    "[Teleportal Shrine Island Overworld] Shiny Spot east of Teleportal Shrine: Item 1": Info(1419, type=Type.SHINY), #SHINE_SEARCH_FG210_1
    "[Teleportal Shrine Island Overworld] Shiny Spot east of Teleportal Shrine: Item 2": Info(1420, type=Type.SHINY_MAX), #SHINE_SEARCH_FG210_2
    "[Teleportal Shrine Island Overworld] Shiny Spot east of Teleportal Shrine: Item 3": Info(1421, type=Type.SHINY_MAX), #SHINE_SEARCH_FG210_3
    "[Teleportal Shrine Island Overworld] Shiny Spot west of Teleportal Shrine: Item 1": Info(1422, type=Type.SHINY), #SHINE_SEARCH_FG204_1
    "[Teleportal Shrine Island Overworld] Shiny Spot west of Teleportal Shrine: Item 2": Info(1423, type=Type.SHINY_MAX), #SHINE_SEARCH_FG204_2
    "[Eastern Overworld] Shiny Spot on the small island south of Teleportal Shrine: Item 1": Info(1424, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG206_1
    "[Eastern Overworld] Shiny Spot on the small island south of Teleportal Shrine: Item 2": Info(1425, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG206_2
    "[Eastern Overworld] Shiny Spot on the small island south-west of Teleportal Shrine: Item 1": Info(1426, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG205_1
    "[Eastern Overworld] Shiny Spot on the small island south-west of Teleportal Shrine: Item 2": Info(1427, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG205_2
    "[Eastern Overworld] Shiny Spot 1 on the small island west of Teleportal Shrine: Item 1": Info(1428, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG207_1
    "[Eastern Overworld] Shiny Spot 1 on the small island west of Teleportal Shrine: Item 2": Info(1429, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG207_2
    "[Eastern Overworld] Shiny Spot 2 on the small island west of Teleportal Shrine: Item 1": Info(1430, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG208_1
    "[Eastern Overworld] Shiny Spot 3 on the small island west of Teleportal Shrine: Item 1": Info(1431, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG209_1
    "[Eastern Overworld] Shiny Spot on the other side of the mountain north-west of Persistence: Item 1": Info(1432, type=Type.SHINY), #SHINE_SEARCH_FG079_1
    "[Eastern Overworld] Shiny Spot on the other side of the mountain north-west of Persistence: Item 2": Info(1433, type=Type.SHINY_MAX), #SHINE_SEARCH_FG079_2
    "[Eastern Overworld] Shiny Spot in the mountain near Spirit Spring: Item 1": Info(1434, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG074_1
    "[Eastern Overworld] Shiny Spot in the mountain near Spirit Spring: Item 2": Info(1435, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG074_2
    "[Eastern Overworld] Shiny Spot in the mountain near Spirit Spring: Item 3": Info(1436, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG074_3
    "[Eastern Overworld] Shiny Spot north-west of Fifer's Spire: Item 1": Info(1437, type=Type.SHINY), #SHINE_SEARCH_FG073_1
    "[Eastern Overworld] Shiny Spot north-west of Fifer's Spire: Item 2": Info(1438, type=Type.SHINY_MAX), #SHINE_SEARCH_FG073_2
    "[Eastern Overworld] Shiny Spot north-west of Fifer's Spire: Item 3": Info(1439, type=Type.SHINY_MAX), #SHINE_SEARCH_FG073_3
    "[Eastern Overworld] Shiny Spot south-east of Fifer's Spire: Item 1": Info(1440, type=Type.SHINY), #SHINE_SEARCH_FG199_1
    "[Eastern Overworld] Shiny Spot south-east of Fifer's Spire: Item 2": Info(1441, type=Type.SHINY_MAX), #SHINE_SEARCH_FG199_2
    "[Eastern Overworld] Shiny Spot south-east of Fifer's Spire: Item 3": Info(1442, type=Type.SHINY_MAX), #SHINE_SEARCH_FG199_3
    "[Eastern Overworld] Shiny Spot near the east coast south-east of Fifer's Spire: Item 1": Info(1443, type=Type.SHINY), #SHINE_SEARCH_FG197_1
    "[Eastern Overworld] Shiny Spot near the east coast south-east of Fifer's Spire: Item 2": Info(1444, type=Type.SHINY_MAX), #SHINE_SEARCH_FG197_2
    "[Eastern Overworld] Shiny Spot near the east coast south-east of Fifer's Spire: Item 3": Info(1445, type=Type.SHINY_MAX), #SHINE_SEARCH_FG197_3
    "[Eastern Overworld] Shiny Spot near the mountain south-east of Fifer's Spire: Item 1": Info(1446, type=Type.SHINY), #SHINE_SEARCH_FG072_1
    "[Eastern Overworld] Shiny Spot near the mountain south-east of Fifer's Spire: Item 2": Info(1447, type=Type.SHINY_MAX), #SHINE_SEARCH_FG072_2
    "[Eastern Overworld] Shiny Spot near the mountain south-east of Fifer's Spire: Item 3": Info(1448, type=Type.SHINY_MAX), #SHINE_SEARCH_FG072_3
    "[Eastern Overworld] Shiny Spot 1 on the coast on the other side of the mountain south of Merchantburg: Item 1": Info(1449, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG191_1
    "[Eastern Overworld] Shiny Spot 1 on the coast on the other side of the mountain south of Merchantburg: Item 2": Info(1450, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG191_2
    "[Eastern Overworld] Shiny Spot 2 on the coast on the other side of the mountain south of Merchantburg: Item 1": Info(1451, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG075_1
    "[Eastern Overworld] Shiny Spot 2 on the coast on the other side of the mountain south of Merchantburg: Item 2": Info(1452, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG075_2
    "[Eastern Overworld] Shiny Spot 2 on the coast on the other side of the mountain south of Merchantburg: Item 3": Info(1453, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG075_3
    "[Eastern Overworld] Shiny Spot on the island after the bridge south-east of Persistence: Item 1": Info(1454, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG188_1
    "[Eastern Overworld] Shiny Spot on the island after the bridge south-east of Persistence: Item 2": Info(1455, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG188_2
    "[Eastern Overworld] Shiny Spot 1 south of Persistence: Item 1": Info(1456, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG189_1
    "[Eastern Overworld] Shiny Spot 1 south of Persistence: Item 2": Info(1457, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG189_2
    "[Eastern Overworld] Shiny Spot 1 south of Persistence: Item 3": Info(1458, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG189_3
    "[Eastern Overworld] Shiny Spot 2 south of Persistence: Item 1": Info(1459, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG190_1
    "[Eastern Overworld] Shiny Spot 2 south of Persistence: Item 2": Info(1460, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG190_2
    "[Eastern Overworld] Shiny Spot 2 south of Persistence: Item 3": Info(1461, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG190_3
    "[Eastern Overworld] Shiny Spot 3 south of Persistence: Item 1": Info(1462, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG192_1
    "[Eastern Overworld] Shiny Spot 3 south of Persistence: Item 2": Info(1463, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG192_2
    "[Eastern Overworld] Shiny Spot south-west of Persistence: Item 1": Info(1464, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG186_1
    "[Eastern Overworld] Shiny Spot south-west of Persistence: Item 2": Info(1465, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG186_2
    "[Eastern Overworld] Shiny Spot on the small coast west of Persistence: Item 1": Info(1466, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG187_1
    "[Eastern Overworld] Shiny Spot on the small coast west of Persistence: Item 2": Info(1467, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG187_2
    "[Eastern Overworld] Shiny Spot north-west of Persistence: Item 1": Info(1468, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG078_1
    "[Eastern Overworld] Shiny Spot north-west of Persistence: Item 2": Info(1469, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG078_2
    "[Eastern Overworld] Shiny Spot in the middle of the poison marsh east of Persistence: Item 1": Info(1470, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG076_1
    "[Eastern Overworld] Shiny Spot in the middle of the poison marsh east of Persistence: Item 2": Info(1471, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG076_2
    "[Eastern Overworld] Shiny Spot near the small coast north-east of Persistence: Item 1": Info(1472, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG196_1
    "[Eastern Overworld] Shiny Spot near the small coast north-east of Persistence: Item 2": Info(1473, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG196_2
    "[Eastern Overworld] Shiny Spot on the small coast north-east of Persistence: Item 1": Info(1474, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG077_1
    "[Eastern Overworld] Shiny Spot on the small coast north-east of Persistence: Item 2": Info(1475, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG077_2
    "[Eastern Overworld] Shiny Spot on the small coast north-east of Persistence: Item 3": Info(1476, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG077_3
    "[Eastern Overworld] Shiny Spot 1 near the mountain north-east of Persistence: Item 1": Info(1477, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG193_1
    "[Eastern Overworld] Shiny Spot 2 near the mountain north-east of Persistence: Item 1": Info(1478, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG194_1
    "[Eastern Overworld] Shiny Spot 2 near the mountain north-east of Persistence: Item 2": Info(1479, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG194_2
    "[Eastern Overworld] Shiny Spot 3 near the mountain north-east of Persistence: Item 1": Info(1480, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG195_1
    "[Eastern Overworld] Shiny Spot in the desert area south-east of Fifer's Spire: Item 1": Info(1481, type=Type.SHINY), #SHINE_SEARCH_FG198_1
    "[Eastern Overworld] Shiny Spot in the desert area south-east of Fifer's Spire: Item 2": Info(1482, type=Type.SHINY_MAX), #SHINE_SEARCH_FG198_2
    "[Eastern Overworld] Shiny Spot in the desert area south-east of Fifer's Spire: Item 3": Info(1483, type=Type.SHINY_MAX), #SHINE_SEARCH_FG198_3
    "[Eastern Overworld] Shiny Spot in the mountain south-east of Fifer's Spire: Item 1": Info(1484, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG071_1
    "[Eastern Overworld] Shiny Spot in the mountain south-east of Fifer's Spire: Item 2": Info(1485, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG071_2
    "[Eastern Overworld] Shiny Spot south-west of the desert area south-east of Fifer's Spire: Item 1": Info(1486, type=Type.SHINY), #SHINE_SEARCH_FG070_1
    "[Eastern Overworld] Shiny Spot south-west of the desert area south-east of Fifer's Spire: Item 2": Info(1487, type=Type.SHINY_MAX), #SHINE_SEARCH_FG070_2
    "[Eastern Overworld] Shiny Spot south-west of the desert area south-east of Fifer's Spire: Item 3": Info(1488, type=Type.SHINY_MAX), #SHINE_SEARCH_FG070_3
    "[Eastern Overworld] Shiny Spot behind the mountain north-west of Manoza: Item 1": Info(1489, type=Type.SHINY), #SHINE_SEARCH_FG200_1
    "[Eastern Overworld] Shiny Spot behind the mountain north-west of Manoza: Item 2": Info(1490, type=Type.SHINY_MAX), #SHINE_SEARCH_FG200_2
    "[Eastern Overworld] Shiny Spot in the mountain west of Manoza: Item 1": Info(1491, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG069_1
    "[Eastern Overworld] Shiny Spot in the mountain west of Manoza: Item 2": Info(1492, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG069_2
    "[Eastern Overworld] Shiny Spot in the mountain west of Manoza: Item 3": Info(1493, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG069_3
    "[Eastern Overworld] Shiny Spot behind the mountain south-west of Manoza: Item 1": Info(1494, type=Type.SHINY), #SHINE_SEARCH_FG065_1
    "[Eastern Overworld] Shiny Spot behind the mountain south-west of Manoza: Item 2": Info(1495, type=Type.SHINY_MAX), #SHINE_SEARCH_FG065_2
    "[Eastern Overworld] Shiny Spot behind the mountain south-west of Manoza: Item 3": Info(1496, type=Type.SHINY_MAX), #SHINE_SEARCH_FG065_3
    "[Eastern Overworld] Shiny Spot behind the mountain south of Manoza: Item 1": Info(1497, type=Type.SHINY), #SHINE_SEARCH_FG064_1
    "[Eastern Overworld] Shiny Spot behind the mountain south of Manoza: Item 2": Info(1498, type=Type.SHINY_MAX), #SHINE_SEARCH_FG064_2
    "[Eastern Overworld] Shiny Spot south-west of Manoza Cave: Item 1": Info(1499, type=Type.SHINY), #SHINE_SEARCH_FG182_1
    "[Eastern Overworld] Shiny Spot south-west of Manoza Cave: Item 2": Info(1500, type=Type.SHINY_MAX), #SHINE_SEARCH_FG182_2
    "[Eastern Overworld] Shiny Spot south-west of Manoza Cave: Item 3": Info(1501, type=Type.SHINY_MAX), #SHINE_SEARCH_FG182_3
    "[Eastern Overworld] Shiny Spot 1 south of Manoza Cave: Item 1": Info(1502, type=Type.SHINY), #SHINE_SEARCH_FG181_1
    "[Eastern Overworld] Shiny Spot 2 south of Manoza Cave: Item 1": Info(1503, type=Type.SHINY), #SHINE_SEARCH_FG183_1
    "[Eastern Overworld] Shiny Spot 3 south of Manoza Cave: Item 1": Info(1504, type=Type.SHINY), #SHINE_SEARCH_FG184_1
    "[Eastern Overworld] Shiny Spot 3 south of Manoza Cave: Item 2": Info(1505, type=Type.SHINY_MAX), #SHINE_SEARCH_FG184_2
    "[Eastern Overworld] Shiny Spot east of Manoza Cave: Item 1": Info(1506, type=Type.SHINY), #SHINE_SEARCH_FG063_1
    "[Eastern Overworld] Shiny Spot east of Manoza Cave: Item 2": Info(1507, type=Type.SHINY_MAX), #SHINE_SEARCH_FG063_2
    "[Eastern Overworld] Shiny Spot east of Manoza Cave: Item 3": Info(1508, type=Type.SHINY_MAX), #SHINE_SEARCH_FG063_3
    "[Eastern Overworld] Shiny Spot near the coast east of Manoza Cave: Item 1": Info(1509, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG067_1
    "[Eastern Overworld] Shiny Spot near the coast east of Manoza Cave: Item 2": Info(1510, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG067_2
    "[Eastern Overworld] Shiny Spot near the coast east of Manoza Cave: Item 3": Info(1511, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG067_3
    "[Eastern Overworld] Shiny Spot north-west of Pirates' Den: Item 1": Info(1512, type=Type.SHINY), #SHINE_SEARCH_FG180_1
    "[Eastern Overworld] Shiny Spot north-west of Pirates' Den: Item 2": Info(1513, type=Type.SHINY_MAX), #SHINE_SEARCH_FG180_2
    "[Eastern Overworld] Shiny Spot 1 on the small coast west of Pirates' Den: Item 1": Info(1514, type=Type.SHINY), #SHINE_SEARCH_FG062_1
    "[Eastern Overworld] Shiny Spot 1 on the small coast west of Pirates' Den: Item 2": Info(1515, type=Type.SHINY_MAX), #SHINE_SEARCH_FG062_2
    "[Eastern Overworld] Shiny Spot 1 on the small coast west of Pirates' Den: Item 3": Info(1516, type=Type.SHINY_MAX), #SHINE_SEARCH_FG062_3
    "[Eastern Overworld] Shiny Spot 2 on the small coast west of Pirates' Den: Item 1": Info(1517, type=Type.SHINY), #SHINE_SEARCH_FG179_1
    "[Eastern Overworld] Shiny Spot 2 on the small coast west of Pirates' Den: Item 2": Info(1518, type=Type.SHINY_MAX), #SHINE_SEARCH_FG179_2
    "[Eastern Overworld] Shiny Spot south of Pirates' Den: Item 1": Info(1519, type=Type.SHINY), #SHINE_SEARCH_FG178_1
    "[Eastern Overworld] Shiny Spot south of Pirates' Den: Item 2": Info(1520, type=Type.SHINY_MAX), #SHINE_SEARCH_FG178_2
    # ----- Southern Mountains Overworld -----
    # 209 071 073 075 077 206 079 080 229 084 201 202 207
    "[Southern Mountains Overworld] Shiny Spot near the north coast and the mountains north of Wayfarer's Shrine: Item 1": Info(1521, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG024_1
    "[Southern Mountains Overworld] Shiny Spot near the north coast and the mountains north of Wayfarer's Shrine: Item 2": Info(1522, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG024_2
    "[Southern Mountains Overworld] Shiny Spot near the north coast on the island north of Wayfarer's Shrine: Item 1": Info(1523, type=Type.SHINY), #SHINE_SEARCH_FG025_1
    "[Southern Mountains Overworld] Shiny Spot near the north coast on the island north of Wayfarer's Shrine: Item 2": Info(1524, type=Type.SHINY_MAX), #SHINE_SEARCH_FG025_2
    "[Southern Mountains Overworld] Shiny Spot near the north coast on the island north of Wayfarer's Shrine: Item 3": Info(1525, type=Type.SHINY_MAX), #SHINE_SEARCH_FG025_3
    "[Southern Mountains Overworld] Shiny Spot north of Wayfarer's Shrine: Item 1": Info(1526, type=Type.SHINY), #SHINE_SEARCH_FG173_1
    "[Southern Mountains Overworld] Shiny Spot north of Wayfarer's Shrine: Item 2": Info(1527, type=Type.SHINY_MAX), #SHINE_SEARCH_FG173_2
    "[Southern Mountains Overworld] Shiny Spot near the mountains east of Wayfarer's Shrine: Item 1": Info(1528, type=Type.SHINY), #SHINE_SEARCH_FG026_1
    "[Southern Mountains Overworld] Shiny Spot near the mountains east of Wayfarer's Shrine: Item 2": Info(1529, type=Type.SHINY_MAX), #SHINE_SEARCH_FG026_2
    "[Southern Mountains Overworld] Shiny Spot near the mountains east of Wayfarer's Shrine: Item 3": Info(1530, type=Type.SHINY_MAX), #SHINE_SEARCH_FG026_3
    "[Southern Mountains Overworld] Shiny Spot on a small coast near the mountains north of Theddon: Item 1": Info(1531, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG029_1
    "[Southern Mountains Overworld] Shiny Spot on a small coast near the mountains north of Theddon: Item 2": Info(1532, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG029_2
    "[Southern Mountains Overworld] Shiny Spot on a small coast near the mountains north of Theddon: Item 3": Info(1533, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG029_3
    "[Southern Mountains Overworld] Shiny Spot in the mountain north-west of Theddon: Item 1": Info(1534, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG027_1
    "[Southern Mountains Overworld] Shiny Spot in the mountain north-west of Theddon: Item 2": Info(1535, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG027_2
    "[Southern Mountains Overworld] Shiny Spot in the mountain north-west of Theddon: Item 3": Info(1536, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG027_3
    "[Southern Mountains Overworld] Shiny Spot south-west of Theddon: Item 1": Info(1537, type=Type.SHINY), #SHINE_SEARCH_FG161_1
    "[Southern Mountains Overworld] Shiny Spot south-west of Theddon: Item 2": Info(1538, type=Type.SHINY_MAX), #SHINE_SEARCH_FG161_2
    "[Southern Mountains Overworld] Shiny Spot south-west of Theddon: Item 3": Info(1539, type=Type.SHINY_MAX), #SHINE_SEARCH_FG161_3
    "[Southern Mountains Overworld] Shiny Spot south of Theddon: Item 1": Info(1540, type=Type.SHINY), #SHINE_SEARCH_FG028_1
    "[Southern Mountains Overworld] Shiny Spot south of Theddon: Item 2": Info(1541, type=Type.SHINY_MAX), #SHINE_SEARCH_FG028_2
    "[Southern Mountains Overworld] Shiny Spot south-east of Theddon: Item 1": Info(1542, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG030_1
    "[Southern Mountains Overworld] Shiny Spot south-east of Theddon: Item 2": Info(1543, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG030_2
    "[Southern Mountains Overworld] Shiny Spot south-east of Theddon: Item 3": Info(1544, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG030_3
    "[Southern Mountains Overworld] Shiny Spot on a small coast east of Theddon: Item 1": Info(1545, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG165_1
    "[Southern Mountains Overworld] Shiny Spot on a small coast east of Theddon: Item 2": Info(1546, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG165_2
    "[Southern Mountains Overworld] Shiny Spot on a small coast east of Theddon: Item 3": Info(1547, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG165_3
    "[Southern Mountains Overworld] Shiny Spot south of Mt. Necrogond: Item 1": Info(1548, (rules.HAS_SHIP & rules.HAS_MOUNTAINCLEAVER) | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG032_1
    "[Southern Mountains Overworld] Shiny Spot south of Mt. Necrogond: Item 2": Info(1549, (rules.HAS_SHIP & rules.HAS_MOUNTAINCLEAVER) | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG032_2
    "[Southern Mountains Overworld] Shiny Spot south of Mt. Necrogond: Item 3": Info(1550, (rules.HAS_SHIP & rules.HAS_MOUNTAINCLEAVER) | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG032_3
    "[Southern Mountains Overworld] Shiny Spot in the middle of the poison marsh east of Maw of the Necrogond: Item 1": Info(1551, (rules.HAS_SHIP & rules.HAS_MOUNTAINCLEAVER) | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG166_1
    "[Southern Mountains Overworld] Shiny Spot in the middle of the poison marsh east of Maw of the Necrogond: Item 2": Info(1552, (rules.HAS_SHIP & rules.HAS_MOUNTAINCLEAVER) | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG166_2
    "[Southern Mountains Overworld] Shiny Spot in the middle of the poison marsh east of Maw of the Necrogond: Item 3": Info(1553, (rules.HAS_SHIP & rules.HAS_MOUNTAINCLEAVER) | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG166_3
    "[Southern Mountains Overworld] Shiny Spot in the mountain east of Maw of the Necrogond: Item 1": Info(1554, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG031_1
    "[Southern Mountains Overworld] Shiny Spot in the mountain east of Maw of the Necrogond: Item 2": Info(1555, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG031_2
    "[Southern Mountains Overworld] Shiny Spot in the mountain east of Maw of the Necrogond: Item 3": Info(1556, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG031_3
    # ----- Manoza Overworld -----
    # 196 197 198 199 200 224
    "[Manoza Overworld] Shiny Spot west of Wayfarer's Chapel: Item 1": Info(1557, type=Type.SHINY), #SHINE_SEARCH_FG201_1
    "[Manoza Overworld] Shiny Spot west of Wayfarer's Chapel: Item 2": Info(1558, type=Type.SHINY_MAX), #SHINE_SEARCH_FG201_2
    "[Manoza Overworld] Shiny Spot between the mountains north-west of Wayfarer's Chapel: Item 1": Info(1559, type=Type.SHINY), #SHINE_SEARCH_FG068_1
    "[Manoza Overworld] Shiny Spot between the mountains north-west of Wayfarer's Chapel: Item 2": Info(1560, type=Type.SHINY_MAX), #SHINE_SEARCH_FG068_2
    "[Manoza Overworld] Shiny Spot between the mountains north-west of Wayfarer's Chapel: Item 3": Info(1561, type=Type.SHINY_MAX), #SHINE_SEARCH_FG068_3
    "[Manoza Overworld] Shiny Spot east of Manoza: Item 1": Info(1562, type=Type.SHINY), #SHINE_SEARCH_FG202_1
    "[Manoza Overworld] Shiny Spot east of Manoza: Item 2": Info(1563, type=Type.SHINY_MAX), #SHINE_SEARCH_FG202_2
    "[Manoza Overworld] Shiny Spot east of Manoza: Item 3": Info(1564, type=Type.SHINY_MAX), #SHINE_SEARCH_FG202_3
    "[Manoza Overworld] Shiny Spot in the poison marsh south-east of Manoza: Item 1": Info(1565, type=Type.SHINY), #SHINE_SEARCH_FG185_1
    "[Manoza Overworld] Shiny Spot in the poison marsh south-east of Manoza: Item 2": Info(1566, type=Type.SHINY_MAX), #SHINE_SEARCH_FG185_2
    "[Manoza Overworld] Shiny Spot south of Manoza: Item 1": Info(1567, type=Type.SHINY), #SHINE_SEARCH_FG203_1
    "[Manoza Overworld] Shiny Spot south of Manoza: Item 2": Info(1568, type=Type.SHINY_MAX), #SHINE_SEARCH_FG203_2
    "[Manoza Overworld] Shiny Spot in the mountain south-east of Manoza: Item 1": Info(1569, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG066_1
    "[Manoza Overworld] Shiny Spot in the mountain south-east of Manoza: Item 2": Info(1570, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG066_2
    "[Manoza Overworld] Shiny Spot in the mountain south-east of Manoza: Item 3": Info(1571, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG066_3
    # ----- Ocean Overworld -----
    # 205 133 132 204 136 137 138 203 143 067 068(2) 169 170 171 228 064 065 130 128 127 126 124 123 109 118
    # 119 120 121 122 070(2) 072 074 076 078 081 082 083 134 135 139 088 085 087 089 140 142 144 145 149 094
    # 156 096 163 099 164 098 100 167 111 112 230 175 172 178 179 180 181 190
    "[Ocean Overworld] Shiny Spot in the mountain west of Shrine of the Everbird: Item 1": Info(1572, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG060_1
    "[Ocean Overworld] Shiny Spot in the mountain west of Shrine of the Everbird: Item 2": Info(1573, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG060_2
    "[Ocean Overworld] Shiny Spot near Shrine of the Everbird: Item 1": Info(1574, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG216_1
    "[Ocean Overworld] Shiny Spot north-east of Shrine of the Everbird: Item 1": Info(1575, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG217_1
    "[Ocean Overworld] Shiny Spot north-east of Shrine of the Everbird: Item 2": Info(1576, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG217_2
    "[Ocean Overworld] Shiny Spot in the mountain east of Shrine of the Everbird: Item 1": Info(1577, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG059_1
    "[Ocean Overworld] Shiny Spot in the mountain east of Shrine of the Everbird: Item 2": Info(1578, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG059_2
    "[Ocean Overworld] Shiny Spot south-east of Lanson: Item 1": Info(1579, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG057_1
    "[Ocean Overworld] Shiny Spot south-east of Lanson: Item 2": Info(1580, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG057_2
    "[Ocean Overworld] Shiny Spot south-east of Lanson: Item 3": Info(1581, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG057_3
    "[Ocean Overworld] Shiny Spot north of Lanson: Item 1": Info(1582, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG168_1
    "[Ocean Overworld] Shiny Spot north of Lanson: Item 2": Info(1583, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG168_2
    "[Ocean Overworld] Shiny Spot north of Lanson: Item 3": Info(1584, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG168_3
    "[Ocean Overworld] Shiny Spot near Gaia's Navel: Item 1": Info(1585, (rules.HAS_SHIP | rules.HAS_BIRD) & rules.HAS_ULTIMATE_KEY, type=Type.SHINY), #SHINE_SEARCH_FG167_1
    "[Ocean Overworld] Shiny Spot near Gaia's Navel: Item 2": Info(1586, (rules.HAS_SHIP | rules.HAS_BIRD) & rules.HAS_ULTIMATE_KEY, type=Type.SHINY_MAX), #SHINE_SEARCH_FG167_2
    "[Ocean Overworld] Shiny Spot in the mountain south-west of Lanson: Item 1": Info(1587, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG058_1
    "[Ocean Overworld] Shiny Spot in the mountain south-west of Lanson: Item 2": Info(1588, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG058_2
    "[Ocean Overworld] Shiny Spot on a small island north of the Aliahan Overworld: Item 1": Info(1589, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG061_1
    "[Ocean Overworld] Shiny Spot on a small island north of the Aliahan Overworld: Item 2": Info(1590, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG061_2
    "[Ocean Overworld] Shiny Spot on a small island north of the Aliahan Overworld: Item 3": Info(1591, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG061_3
    "[Ocean Overworld] Shiny Spot 1 on a small island south-east of Romaria: Item 1": Info(1592, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG017_1
    "[Ocean Overworld] Shiny Spot 1 on a small island south-east of Romaria: Item 2": Info(1593, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG017_2
    "[Ocean Overworld] Shiny Spot 1 on a small island south-east of Romaria: Item 3": Info(1594, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG017_3
    "[Ocean Overworld] Shiny Spot 2 on a small island south-east of Romaria: Item 1": Info(1595, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG174_1
    "[Ocean Overworld] Shiny Spot 2 on a small island south-east of Romaria: Item 2": Info(1596, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG174_2
    "[Ocean Overworld] Shiny Spot 2 on a small island south-east of Romaria: Item 3": Info(1597, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG174_3
    "[Ocean Overworld] Shiny Spot 3 on a small island south-east of Romaria: Item 1": Info(1598, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG175_1
    "[Ocean Overworld] Shiny Spot 3 on a small island south-east of Romaria: Item 2": Info(1599, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG175_2
    "[Ocean Overworld] Shiny Spot west of Grimland: Item 1": Info(1600, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG211_1
    "[Ocean Overworld] Shiny Spot west of Grimland: Item 2": Info(1601, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG211_2
    "[Ocean Overworld] Shiny Spot west of Grimland: Item 3": Info(1602, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG211_3
    "[Ocean Overworld] Shiny Spot on a small coast north-west of Grimland: Item 1": Info(1603, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG080_1
    "[Ocean Overworld] Shiny Spot on a small coast north-west of Grimland: Item 2": Info(1604, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG080_2
    "[Ocean Overworld] Shiny Spot north-east of Grimland: Item 1": Info(1605, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG212_1
    "[Ocean Overworld] Shiny Spot north-east of Grimland: Item 2": Info(1606, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG212_2
    "[Ocean Overworld] Shiny Spot in the mountain east of Grimland: Item 1": Info(1607, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG082_1
    "[Ocean Overworld] Shiny Spot in the mountain east of Grimland: Item 2": Info(1608, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG082_2
    "[Ocean Overworld] Shiny Spot in the mountain east of Grimland: Item 3": Info(1609, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG082_3
    "[Ocean Overworld] Shiny Spot near Portoga: Item 1": Info(1610, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS040_1
    "[Ocean Overworld] Shiny Spot near Portoga: Item 2": Info(1611, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS040_2
    "[Ocean Overworld] Shiny Spot near Portoga: Item 3": Info(1612, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS040_3
    "[Ocean Overworld] Shiny Spot west of Romaria: Item 1": Info(1613, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS001_1
    "[Ocean Overworld] Shiny Spot west of Romaria: Item 2": Info(1614, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS001_2
    "[Ocean Overworld] Shiny Spot west of Romaria: Item 3": Info(1615, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS001_3
    "[Ocean Overworld] Shiny Spot west of Skyfell Tower: Item 1": Info(1616, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS002_1
    "[Ocean Overworld] Shiny Spot west of Skyfell Tower: Item 2": Info(1617, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS002_2
    "[Ocean Overworld] Shiny Spot west of Skyfell Tower: Item 3": Info(1618, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS002_3
    "[Ocean Overworld] Shiny Spot north-west of Edina Castle: Item 1": Info(1619, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS051_1
    "[Ocean Overworld] Shiny Spot north-west of Edina Castle: Item 2": Info(1620, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS051_2
    "[Ocean Overworld] Shiny Spot north-west of Edina Castle: Item 3": Info(1621, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS051_3
    "[Ocean Overworld] Shiny Spot north-west of Faerie Village: Item 1": Info(1622, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS052_1
    "[Ocean Overworld] Shiny Spot north-west of Faerie Village: Item 2": Info(1623, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS052_2
    "[Ocean Overworld] Shiny Spot north-west of Faerie Village: Item 3": Info(1624, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS052_3
    "[Ocean Overworld] Shiny Spot south-east of Faerie Village: Item 1": Info(1625, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS003_1
    "[Ocean Overworld] Shiny Spot south-east of Faerie Village: Item 2": Info(1626, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS003_2
    "[Ocean Overworld] Shiny Spot 1 north-east of Norvik: Item 1": Info(1627, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS054_1
    "[Ocean Overworld] Shiny Spot 1 north-east of Norvik: Item 2": Info(1628, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS054_2
    "[Ocean Overworld] Shiny Spot 1 north-east of Norvik: Item 3": Info(1629, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS054_3
    "[Ocean Overworld] Shiny Spot 2 north-east of Norvik: Item 1": Info(1630, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS053_1
    "[Ocean Overworld] Shiny Spot 2 north-east of Norvik: Item 2": Info(1631, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS053_2
    "[Ocean Overworld] Shiny Spot east of Olivia's Promontory: Item 1": Info(1632, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS017_1
    "[Ocean Overworld] Shiny Spot east of Olivia's Promontory: Item 2": Info(1633, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS017_2
    "[Ocean Overworld] Shiny Spot east of Olivia's Promontory: Item 3": Info(1634, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS017_3
    "[Ocean Overworld] Shiny Spot west of Shrine of Shackles: Item 1": Info(1635, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY), #SHINE_SEARCH_FS016_1
    "[Ocean Overworld] Shiny Spot west of Shrine of Shackles: Item 2": Info(1636, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY_MAX), #SHINE_SEARCH_FS016_2
    "[Ocean Overworld] Shiny Spot west of Shrine of Shackles: Item 3": Info(1637, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY_MAX), #SHINE_SEARCH_FS016_3
    "[Ocean Overworld] Shiny Spot 1 in the river north of Shrine of Shackles: Item 1": Info(1638, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY), #SHINE_SEARCH_FS059_1
    "[Ocean Overworld] Shiny Spot 1 in the river north of Shrine of Shackles: Item 2": Info(1639, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY_MAX), #SHINE_SEARCH_FS059_2
    "[Ocean Overworld] Shiny Spot 2 in the river north of Shrine of Shackles: Item 1": Info(1640, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY), #SHINE_SEARCH_FS058_1
    "[Ocean Overworld] Shiny Spot 3 in the river north of Shrine of Shackles: Item 1": Info(1641, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY), #SHINE_SEARCH_FS057_1
    "[Ocean Overworld] Shiny Spot 4 in the river north of Shrine of Shackles: Item 1": Info(1642, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY), #SHINE_SEARCH_FS014_1
    "[Ocean Overworld] Shiny Spot 4 in the river north of Shrine of Shackles: Item 2": Info(1643, rules.HAS_SHIP & rules.HAS_LOVERS_LOCKET, type=Type.SHINY_MAX), #SHINE_SEARCH_FS014_2
    "[Ocean Overworld] Shiny Spot in the river south of Asham: Item 1": Info(1644, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS008_1
    "[Ocean Overworld] Shiny Spot in the river south of Asham: Item 2": Info(1645, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS008_2
    "[Ocean Overworld] Shiny Spot in the river south of Asham: Item 3": Info(1646, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS008_3
    "[Ocean Overworld] Shiny Spot 1 south-west of Portoga Lighthouse: Item 1": Info(1647, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS000_1
    "[Ocean Overworld] Shiny Spot 1 south-west of Portoga Lighthouse: Item 2": Info(1648, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS000_2
    "[Ocean Overworld] Shiny Spot 1 south-west of Portoga Lighthouse: Item 3": Info(1649, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS000_3
    "[Ocean Overworld] Shiny Spot 2 south-west of Portoga Lighthouse: Item 1": Info(1650, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS060_1
    "[Ocean Overworld] Shiny Spot 2 south-west of Portoga Lighthouse: Item 2": Info(1651, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS060_2
    "[Ocean Overworld] Shiny Spot 2 south-west of Portoga Lighthouse: Item 3": Info(1652, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS060_3
    "[Ocean Overworld] Shiny Spot north-west of Wayfarer's Shrine: Item 1": Info(1653, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS061_1
    "[Ocean Overworld] Shiny Spot north-west of Wayfarer's Shrine: Item 2": Info(1654, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS061_2
    "[Ocean Overworld] Shiny Spot north-west of Wayfarer's Shrine: Item 3": Info(1655, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS061_3
    "[Ocean Overworld] Shiny Spot west of Wayfarer's Shrine: Item 1": Info(1656, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS004_1
    "[Ocean Overworld] Shiny Spot west of Wayfarer's Shrine: Item 2": Info(1657, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS004_2
    "[Ocean Overworld] Shiny Spot in the river north-west of Theddon: Item 1": Info(1658, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS042_1
    "[Ocean Overworld] Shiny Spot in the river north-west of Theddon: Item 2": Info(1659, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS042_2
    "[Ocean Overworld] Shiny Spot in the river west of Theddon: Item 1": Info(1660, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS005_1
    "[Ocean Overworld] Shiny Spot west of Theddon: Item 1": Info(1661, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS041_1
    "[Ocean Overworld] Shiny Spot west of Theddon: Item 2": Info(1662, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS041_2
    "[Ocean Overworld] Shiny Spot north-west of Shrine of the Everbird: Item 1": Info(1663, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS006_1
    "[Ocean Overworld] Shiny Spot north-west of Shrine of the Everbird: Item 2": Info(1664, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS006_2
    "[Ocean Overworld] Shiny Spot north of Shrine of the Everbird: Item 1": Info(1665, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS044_1
    "[Ocean Overworld] Shiny Spot north of Shrine of the Everbird: Item 2": Info(1666, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS044_2
    "[Ocean Overworld] Shiny Spot 1 south of Lanson: Item 1": Info(1667, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS067_1
    "[Ocean Overworld] Shiny Spot 1 south of Lanson: Item 2": Info(1668, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS067_2
    "[Ocean Overworld] Shiny Spot 2 south of Lanson: Item 1": Info(1669, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS045_1
    "[Ocean Overworld] Shiny Spot 2 south of Lanson: Item 2": Info(1670, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS045_2
    "[Ocean Overworld] Shiny Spot north-west of Lanson: Item 1": Info(1671, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS007_1
    "[Ocean Overworld] Shiny Spot north-west of Lanson: Item 2": Info(1672, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS007_2
    "[Ocean Overworld] Shiny Spot north of Lanson: Item 1": Info(1673, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS046_1
    "[Ocean Overworld] Shiny Spot north of Lanson: Item 2": Info(1674, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS046_2
    "[Ocean Overworld] Shiny Spot north of Lanson: Item 3": Info(1675, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS046_3
    "[Ocean Overworld] Shiny Spot east of Lanson: Item 1": Info(1676, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS043_1
    "[Ocean Overworld] Shiny Spot east of Lanson: Item 2": Info(1677, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS043_2
    "[Ocean Overworld] Shiny Spot south-west of Promontory Passage: Item 1": Info(1678, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS010_1
    "[Ocean Overworld] Shiny Spot south-west of Promontory Passage: Item 2": Info(1679, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS010_2
    "[Ocean Overworld] Shiny Spot south-west of Promontory Passage: Item 3": Info(1680, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS010_3
    "[Ocean Overworld] Shiny Spot north of Reeve: Item 1": Info(1681, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS009_1
    "[Ocean Overworld] Shiny Spot north of Reeve: Item 2": Info(1682, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS009_2
    "[Ocean Overworld] Shiny Spot north of Reeve: Item 3": Info(1683, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS009_3
    "[Ocean Overworld] Shiny Spot east of Path of Promise: Item 1": Info(1684, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS011_1
    "[Ocean Overworld] Shiny Spot east of Path of Promise: Item 2": Info(1685, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS011_2
    "[Ocean Overworld] Shiny Spot east of Path of Promise: Item 3": Info(1686, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS011_3
    "[Ocean Overworld] Shiny Spot north of Lozamii: Item 1": Info(1687, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS012_1
    "[Ocean Overworld] Shiny Spot north of Lozamii: Item 2": Info(1688, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS012_2
    "[Ocean Overworld] Shiny Spot east of Lozamii: Item 1": Info(1689, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS064_1
    "[Ocean Overworld] Shiny Spot east of Lozamii: Item 2": Info(1690, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS064_2
    "[Ocean Overworld] Shiny Spot east of Lozamii: Item 3": Info(1691, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS064_3
    "[Ocean Overworld] Shiny Spot north-east of Pirates' Den: Item 1": Info(1692, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS055_1
    "[Ocean Overworld] Shiny Spot north-east of Pirates' Den: Item 2": Info(1693, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS055_2
    "[Ocean Overworld] Shiny Spot north-east of Pirates' Den: Item 3": Info(1694, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS055_3
    "[Ocean Overworld] Shiny Spot east of Jipang: Item 1": Info(1695, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS056_1
    "[Ocean Overworld] Shiny Spot east of Jipang: Item 2": Info(1696, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS056_2
    "[Ocean Overworld] Shiny Spot east of Jipang: Item 3": Info(1697, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS056_3
    "[Ocean Overworld] Shiny Spot south of Fifer's Spire: Item 1": Info(1698, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS024_1
    "[Ocean Overworld] Shiny Spot south of Fifer's Spire: Item 2": Info(1699, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS024_2
    "[Ocean Overworld] Shiny Spot south of Fifer's Spire: Item 3": Info(1700, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS024_3
    "[Ocean Overworld] Shiny Spot south-east of Mur: Item 1": Info(1701, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS023_1
    "[Ocean Overworld] Shiny Spot south-east of Mur: Item 2": Info(1702, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS023_2
    "[Ocean Overworld] Shiny Spot south-east of Mur: Item 3": Info(1703, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS023_3
    "[Ocean Overworld] Shiny Spot north-west of Fifer's Spire: Item 1": Info(1704, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS021_1
    "[Ocean Overworld] Shiny Spot north-west of Fifer's Spire: Item 2": Info(1705, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS021_2
    "[Ocean Overworld] Shiny Spot north-west of Fifer's Spire: Item 3": Info(1706, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS021_3
    "[Ocean Overworld] Shiny Spot in the river near Tower of Transcendence: Item 1": Info(1707, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS047_1
    "[Ocean Overworld] Shiny Spot in the river near Tower of Transcendence: Item 2": Info(1708, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS047_2
    "[Ocean Overworld] Shiny Spot in the river near Tower of Transcendence: Item 3": Info(1709, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS047_3
    "[Ocean Overworld] Shiny Spot south of Shallows Shrine: Item 1": Info(1710, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS048_1
    "[Ocean Overworld] Shiny Spot south of Shallows Shrine: Item 2": Info(1711, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS048_2
    "[Ocean Overworld] Shiny Spot south of Shallows Shrine: Item 3": Info(1712, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS048_3
    "[Ocean Overworld] Shiny Spot south-east of Shallows Shrine: Item 1": Info(1713, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS050_1
    "[Ocean Overworld] Shiny Spot south-east of Shallows Shrine: Item 2": Info(1714, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS050_2
    "[Ocean Overworld] Shiny Spot west of Shallows Shrine: Item 1": Info(1715, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS068_1
    "[Ocean Overworld] Shiny Spot west of Shallows Shrine: Item 2": Info(1716, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS068_2
    "[Ocean Overworld] Shiny Spot north of Shallows Shrine: Item 1": Info(1717, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS049_1
    "[Ocean Overworld] Shiny Spot north of Shallows Shrine: Item 2": Info(1718, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS049_2
    "[Ocean Overworld] Shiny Spot north of Shallows Shrine: Item 3": Info(1719, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS049_3
    "[Ocean Overworld] Shiny Spot north of Shrine of the Dwarf: Item 1": Info(1720, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS015_1
    "[Ocean Overworld] Shiny Spot north of Shrine of the Dwarf: Item 2": Info(1721, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS015_2
    "[Ocean Overworld] Shiny Spot north of Shrine of the Dwarf: Item 3": Info(1722, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS015_3
    "[Ocean Overworld] Shiny Spot far north of Shrine of the Dwarf: Item 1": Info(1723, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS069_1
    "[Ocean Overworld] Shiny Spot far north of Shrine of the Dwarf: Item 2": Info(1724, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS069_2
    "[Ocean Overworld] Shiny Spot west of Grimland: Item 1": Info(1725, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS018_1
    "[Ocean Overworld] Shiny Spot west of Grimland: Item 2": Info(1726, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS018_2
    "[Ocean Overworld] Shiny Spot west of Grimland: Item 3": Info(1727, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS018_3
    "[Ocean Overworld] Shiny Spot south-west of Teleportal Shrine: Item 1": Info(1728, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS020_1
    "[Ocean Overworld] Shiny Spot south-west of Teleportal Shrine: Item 2": Info(1729, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS020_2
    "[Ocean Overworld] Shiny Spot south-west of Teleportal Shrine: Item 3": Info(1730, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS020_3
    "[Ocean Overworld] Shiny Spot east of Grimland: Item 1": Info(1731, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS078_1
    "[Ocean Overworld] Shiny Spot east of Grimland: Item 2": Info(1732, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS078_2
    "[Ocean Overworld] Shiny Spot east of Grimland: Item 3": Info(1733, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS078_3
    "[Ocean Overworld] Shiny Spot east of Merchantburg: Item 1": Info(1734, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS066_1
    "[Ocean Overworld] Shiny Spot east of Merchantburg: Item 2": Info(1735, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS066_2
    "[Ocean Overworld] Shiny Spot east of Merchantburg: Item 3": Info(1736, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS066_3
    "[Ocean Overworld] Shiny Spot south-east of Merchantburg: Item 1": Info(1737, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS065_1
    "[Ocean Overworld] Shiny Spot south-east of Merchantburg: Item 2": Info(1738, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS065_2
    "[Ocean Overworld] Shiny Spot east of the desert area south-east of Fifer's Spire: Item 1": Info(1739, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS063_1
    "[Ocean Overworld] Shiny Spot east of the desert area south-east of Fifer's Spire: Item 2": Info(1740, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS063_2
    "[Ocean Overworld] Shiny Spot east of the desert area south-east of Fifer's Spire: Item 3": Info(1741, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS063_3
    "[Ocean Overworld] Shiny Spot at the start of the river south-east of Persistence: Item 1": Info(1742, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS062_1
    "[Ocean Overworld] Shiny Spot at the start of the river south-east of Persistence: Item 2": Info(1743, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS062_2
    "[Ocean Overworld] Shiny Spot in the river west of Persistence: Item 1": Info(1744, rules.HAS_SHIP, type=Type.SHINY), #SHINE_SEARCH_FS022_1
    "[Ocean Overworld] Shiny Spot in the river west of Persistence: Item 2": Info(1745, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS022_2
    "[Ocean Overworld] Shiny Spot in the river west of Persistence: Item 3": Info(1746, rules.HAS_SHIP, type=Type.SHINY_MAX), #SHINE_SEARCH_FS022_3
    # ----- Alefgard Overworld -----
    # 
}