from __future__ import annotations

from . import rules
from .data import LocationInfo as Info
from .data import LocationType as Type


# List every extra locations (optional depending on options)
EXTRA_LOCATIONS: dict[str, Info] = {
    # ///////////////////////// SHINY SPOTS /////////////////////////
    # ----- Aliahan Overworld -----
    # 001 002 003 004 005 006 007 008 009 010 141
    "[Aliahan Overworld] Shiny Spot near Aliahan: Item 1": Info(1123, type=Type.SHINY), #SHINE_SEARCH_FG000_1
    "[Aliahan Overworld] Shiny Spot near Aliahan: Item 2": Info(1124, type=Type.SHINY_MAX), #SHINE_SEARCH_FG000_2
    "[Aliahan Overworld] Shiny Spot near Aliahan: Item 3": Info(1125, type=Type.SHINY_MAX), #SHINE_SEARCH_FG000_3
    "[Aliahan Overworld] Shiny Spot south-west of Aliahan: Item 1": Info(1126, type=Type.SHINY), #SHINE_SEARCH_FG114_1
    "[Aliahan Overworld] Shiny Spot south-west of Aliahan: Item 2": Info(1127, type=Type.SHINY_MAX), #SHINE_SEARCH_FG114_2
    "[Aliahan Overworld] Shiny Spot south of Shrine of the Plains: Item 1": Info(1128, type=Type.SHINY), #SHINE_SEARCH_FG001_1
    "[Aliahan Overworld] Shiny Spot south of Shrine of the Plains: Item 2": Info(1129, type=Type.SHINY_MAX), #SHINE_SEARCH_FG001_2
    "[Aliahan Overworld] Shiny Spot south of Shrine of the Plains: Item 3": Info(1130, type=Type.SHINY_MAX), #SHINE_SEARCH_FG001_3
    "[Aliahan Overworld] Shiny Spot north of Promontory Passage: Item 1": Info(1131, type=Type.SHINY), #SHINE_SEARCH_FG120_1
    "[Aliahan Overworld] Shiny Spot north of Promontory Passage: Item 2": Info(1132, type=Type.SHINY_MAX), #SHINE_SEARCH_FG120_2
    "[Aliahan Overworld] Shiny Spot north of Promontory Passage: Item 3": Info(1133, type=Type.SHINY_MAX), #SHINE_SEARCH_FG120_3
    "[Aliahan Overworld] Shiny Spot north-west of Promontory Passage: Item 1": Info(1134, type=Type.SHINY), #SHINE_SEARCH_FG115_1
    "[Aliahan Overworld] Shiny Spot north-west of Promontory Passage: Item 2": Info(1135, type=Type.SHINY_MAX), #SHINE_SEARCH_FG115_2
    "[Aliahan Overworld] Shiny Spot north-west of Promontory Passage: Item 3": Info(1136, type=Type.SHINY_MAX), #SHINE_SEARCH_FG115_3
    "[Aliahan Overworld] Shiny Spot on the west coast of the mountain west of Aliahan: Item 1": Info(1137, type=Type.SHINY), #SHINE_SEARCH_FG116_1
    "[Aliahan Overworld] Shiny Spot on the west coast of the mountain west of Aliahan: Item 2": Info(1138, type=Type.SHINY_MAX), #SHINE_SEARCH_FG116_2
    "[Aliahan Overworld] Shiny Spot on the west coast of the mountain west of Aliahan: Item 3": Info(1139, type=Type.SHINY_MAX), #SHINE_SEARCH_FG116_3
    "[Aliahan Overworld] Shiny Spot south-west of Reeve: Item 1": Info(1140, type=Type.SHINY), #SHINE_SEARCH_FG117_1
    "[Aliahan Overworld] Shiny Spot south-west of Reeve: Item 2": Info(1141, type=Type.SHINY_MAX), #SHINE_SEARCH_FG117_2
    "[Aliahan Overworld] Shiny Spot south-west of Reeve: Item 3": Info(1142, type=Type.SHINY_MAX), #SHINE_SEARCH_FG117_3
    "[Aliahan Overworld] Shiny Spot east of Reeve: Item 1": Info(1143, type=Type.SHINY), #SHINE_SEARCH_FG118_1
    "[Aliahan Overworld] Shiny Spot east of Reeve: Item 2": Info(1144, type=Type.SHINY_MAX), #SHINE_SEARCH_FG118_2
    "[Aliahan Overworld] Shiny Spot near the river north-west of Little Shrine: Item 1": Info(1145, type=Type.SHINY), #SHINE_SEARCH_FG003_1
    "[Aliahan Overworld] Shiny Spot near the river north-west of Little Shrine: Item 2": Info(1146, type=Type.SHINY_MAX), #SHINE_SEARCH_FG003_2
    "[Aliahan Overworld] Shiny Spot near the river north-west of Little Shrine: Item 3": Info(1147, type=Type.SHINY_MAX), #SHINE_SEARCH_FG003_3
    "[Aliahan Overworld] Shiny Spot near Little Shrine: Item 1": Info(1148, type=Type.SHINY), #SHINE_SEARCH_FG119_1
    "[Aliahan Overworld] Shiny Spot near Little Shrine: Item 2": Info(1149, type=Type.SHINY_MAX), #SHINE_SEARCH_FG119_2
    "[Aliahan Overworld] Shiny Spot on a small coast north of Path of Promise: Item 1": Info(1150, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG002_1
    "[Aliahan Overworld] Shiny Spot on a small coast north of Path of Promise: Item 2": Info(1151, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG002_2
    "[Aliahan Overworld] Shiny Spot on a small coast north of Path of Promise: Item 3": Info(1152, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG002_3
    # ----- Northwest Overworld -----
    # 011 066 012 013 214 018 019 014 017 020 021 125 022 016 015 212 023 024 211 231 025 213 129(4)
    "[Northwest Overworld] Shiny Spot north of Romarian Road: Item 1": Info(1153, type=Type.SHINY), #SHINE_SEARCH_FG004_1
    "[Northwest Overworld] Shiny Spot north of Romarian Road: Item 2": Info(1154, type=Type.SHINY_MAX), #SHINE_SEARCH_FG004_2
    "[Northwest Overworld] Shiny Spot on the small island south of Shrine of Promise: Item 1": Info(1155, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG177_1
    "[Northwest Overworld] Shiny Spot on the small island south of Shrine of Promise: Item 2": Info(1156, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG177_2
    "[Northwest Overworld] Shiny Spot on the small island south of Shrine of Promise: Item 3": Info(1157, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG177_3
    "[Northwest Overworld] Shiny Spot north-east of Romarian Road: Item 1": Info(1158, type=Type.SHINY), #SHINE_SEARCH_FG122_1
    "[Northwest Overworld] Shiny Spot north-east of Romarian Road: Item 2": Info(1159, type=Type.SHINY_MAX), #SHINE_SEARCH_FG122_2
    "[Northwest Overworld] Shiny Spot north-east of Romarian Road: Item 3": Info(1160, type=Type.SHINY_MAX), #SHINE_SEARCH_FG122_3
    "[Northwest Overworld] Shiny Spot south of Khoryv: Item 1": Info(1161, type=Type.SHINY), #SHINE_SEARCH_FG121_1
    "[Northwest Overworld] Shiny Spot south of Khoryv: Item 2": Info(1162, type=Type.SHINY_MAX), #SHINE_SEARCH_FG121_2
    "[Northwest Overworld] Shiny Spot south of Khoryv: Item 3": Info(1163, type=Type.SHINY_MAX), #SHINE_SEARCH_FG121_3
    "[Northwest Overworld] Shiny Spot in the mountain south-east of Khoryv: Item 1": Info(1164, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG016_1
    "[Northwest Overworld] Shiny Spot in the mountain south-east of Khoryv: Item 2": Info(1165, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG016_2
    "[Northwest Overworld] Shiny Spot in the mountain south-east of Khoryv: Item 3": Info(1166, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG016_3
    "[Northwest Overworld] Shiny Spot east of Khoryv: Item 1": Info(1167, type=Type.SHINY), #SHINE_SEARCH_FG081_1
    "[Northwest Overworld] Shiny Spot east of Khoryv: Item 2": Info(1168, type=Type.SHINY_MAX), #SHINE_SEARCH_FG081_2
    "[Northwest Overworld] Shiny Spot east of Khoryv: Item 3": Info(1169, type=Type.SHINY_MAX), #SHINE_SEARCH_FG081_3
    "[Northwest Overworld] Shiny Spot on the top edge coast of the snowy mountain north-east of Khoryv: Item 1": Info(1170, type=Type.SHINY), #SHINE_SEARCH_FG015_1
    "[Northwest Overworld] Shiny Spot on the top edge coast of the snowy mountain north-east of Khoryv: Item 2": Info(1171, type=Type.SHINY_MAX), #SHINE_SEARCH_FG015_2
    "[Northwest Overworld] Shiny Spot on the top edge coast of the snowy mountain north-east of Khoryv: Item 3": Info(1172, type=Type.SHINY_MAX), #SHINE_SEARCH_FG015_3
    "[Northwest Overworld] Shiny Spot north of Khoryv: Item 1": Info(1173, type=Type.SHINY), #SHINE_SEARCH_FG123_1
    "[Northwest Overworld] Shiny Spot north of Khoryv: Item 2": Info(1174, type=Type.SHINY_MAX), #SHINE_SEARCH_FG123_2
    "[Northwest Overworld] Shiny Spot north of Khoryv: Item 3": Info(1175, type=Type.SHINY_MAX), #SHINE_SEARCH_FG123_3
    "[Northwest Overworld] Shiny Spot near the coast north of Khoryv: Item 1": Info(1176, type=Type.SHINY), #SHINE_SEARCH_FG128_1
    "[Northwest Overworld] Shiny Spot near the coast north of Khoryv: Item 2": Info(1177, type=Type.SHINY_MAX), #SHINE_SEARCH_FG128_2
    "[Northwest Overworld] Shiny Spot on the coast west of Norvik: Item 1": Info(1178, type=Type.SHINY), #SHINE_SEARCH_FG005_1
    "[Northwest Overworld] Shiny Spot on the coast west of Norvik: Item 2": Info(1179, type=Type.SHINY_MAX), #SHINE_SEARCH_FG005_2
    "[Northwest Overworld] Shiny Spot on the coast west of Norvik: Item 3": Info(1180, type=Type.SHINY_MAX), #SHINE_SEARCH_FG005_3
    "[Northwest Overworld] Shiny Spot east of Faerie Village: Item 1": Info(1181, type=Type.SHINY), #SHINE_SEARCH_FG129_1
    "[Northwest Overworld] Shiny Spot east of Faerie Village: Item 2": Info(1182, type=Type.SHINY_MAX), #SHINE_SEARCH_FG129_2
    "[Northwest Overworld] Shiny Spot on a small coast north-east of Faerie Village: Item 1": Info(1183, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG006_1
    "[Northwest Overworld] Shiny Spot on a small coast north-east of Faerie Village: Item 2": Info(1184, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG006_2
    "[Northwest Overworld] Shiny Spot on a small coast north-east of Faerie Village: Item 3": Info(1185, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG006_3
    "[Northwest Overworld] Shiny Spot near Underground Lake: Item 1": Info(1186, type=Type.SHINY), #SHINE_SEARCH_FG125_1
    "[Northwest Overworld] Shiny Spot near Underground Lake: Item 2": Info(1187, type=Type.SHINY_MAX), #SHINE_SEARCH_FG125_2
    "[Northwest Overworld] Shiny Spot on the coast west of Khoryv: Item 1": Info(1188, type=Type.SHINY), #SHINE_SEARCH_FG124_1
    "[Northwest Overworld] Shiny Spot on the coast west of Khoryv: Item 2": Info(1189, type=Type.SHINY_MAX), #SHINE_SEARCH_FG124_2
    "[Northwest Overworld] Shiny Spot on the coast west of Khoryv: Item 3": Info(1190, type=Type.SHINY_MAX), #SHINE_SEARCH_FG124_3
    "[Northwest Overworld] Shiny Spot south-west of Khoryv: Item 1": Info(1191, type=Type.SHINY), #SHINE_SEARCH_FG007_1
    "[Northwest Overworld] Shiny Spot south-west of Khoryv: Item 2": Info(1192, type=Type.SHINY_MAX), #SHINE_SEARCH_FG007_2
    "[Northwest Overworld] Shiny Spot south-west of Khoryv: Item 3": Info(1193, type=Type.SHINY_MAX), #SHINE_SEARCH_FG007_3
    "[Northwest Overworld] Shiny Spot in the mountain north of Skyfell Tower: Item 1": Info(1194, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG008_1
    "[Northwest Overworld] Shiny Spot in the mountain north of Skyfell Tower: Item 2": Info(1195, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG008_2
    "[Northwest Overworld] Shiny Spot in the mountain north of Skyfell Tower: Item 3": Info(1196, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG008_3
    "[Northwest Overworld] Shiny Spot north of Skyfell Tower: Item 1": Info(1197, type=Type.SHINY), #SHINE_SEARCH_FG126_1
    "[Northwest Overworld] Shiny Spot north of Skyfell Tower: Item 2": Info(1198, type=Type.SHINY_MAX), #SHINE_SEARCH_FG126_2
    "[Northwest Overworld] Shiny Spot near Skyfell Tower: Item 1": Info(1199, type=Type.SHINY), #SHINE_SEARCH_FG127_1
    "[Northwest Overworld] Shiny Spot near Skyfell Tower: Item 2": Info(1200, type=Type.SHINY_MAX), #SHINE_SEARCH_FG127_2
    "[Northwest Overworld] Shiny Spot near Skyfell Tower: Item 3": Info(1201, type=Type.SHINY_MAX), #SHINE_SEARCH_FG127_3
    "[Northwest Overworld] Shiny Spot in the mountain east of Skyfell Tower: Item 1": Info(1202, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG009_1
    "[Northwest Overworld] Shiny Spot in the mountain east of Skyfell Tower: Item 2": Info(1203, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG009_2
    "[Northwest Overworld] Shiny Spot in the mountain east of Skyfell Tower: Item 3": Info(1204, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG009_3
    "[Northwest Overworld] Shiny Spot on the small coast south-east of Skyfell Tower: Item 1": Info(1205, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG010_1
    "[Northwest Overworld] Shiny Spot on the small coast south-east of Skyfell Tower: Item 2": Info(1206, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG010_2
    "[Northwest Overworld] Shiny Spot on the small coast south-east of Skyfell Tower: Item 3": Info(1207, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG010_3
    "[Northwest Overworld] Shiny Spot on the bottom edge coast south of Skyfell Tower: Item 1": Info(1208, type=Type.SHINY), #SHINE_SEARCH_FG011_1
    "[Northwest Overworld] Shiny Spot on the bottom edge coast south of Skyfell Tower: Item 2": Info(1209, type=Type.SHINY_MAX), #SHINE_SEARCH_FG011_2
    "[Northwest Overworld] Shiny Spot on the bottom edge coast south of Skyfell Tower: Item 3": Info(1210, type=Type.SHINY_MAX), #SHINE_SEARCH_FG011_3
    "[Northwest Overworld] Shiny Spot in the mountain north of Edina Castle: Item 1": Info(1211, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG013_1
    "[Northwest Overworld] Shiny Spot in the mountain north of Edina Castle: Item 2": Info(1212, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG013_2
    "[Northwest Overworld] Shiny Spot 1 on the island west of Edina Castle: Item 1": Info(1213, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG164_1
    "[Northwest Overworld] Shiny Spot 1 on the island west of Edina Castle: Item 2": Info(1214, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG164_2
    "[Northwest Overworld] Shiny Spot 2 on the island west of Edina Castle: Item 1": Info(1215, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG163_1
    "[Northwest Overworld] Shiny Spot 3 on the island west of Edina Castle: Item 1": Info(1216, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG162_1
    "[Northwest Overworld] Shiny Spot 3 on the island west of Edina Castle: Item 2": Info(1217, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG162_2
    "[Northwest Overworld] Shiny Spot 4 on the island west of Edina Castle: Item 1": Info(1218, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG014_1
    # ----- Great Desert Overworld -----
    # 026 027 028 029 069(2) 030 031 032 216 033 039 038 037(3) 035 034 208 036
    "[Great Desert Overworld] Shiny Spot south of the bridge between Asham and Romaria: Item 1": Info(1219, type=Type.SHINY), #SHINE_SEARCH_FG130_1
    "[Great Desert Overworld] Shiny Spot south of the bridge between Asham and Romaria: Item 2": Info(1220, type=Type.SHINY_MAX), #SHINE_SEARCH_FG130_2
    "[Great Desert Overworld] Shiny Spot south of the bridge between Asham and Romaria: Item 3": Info(1221, type=Type.SHINY_MAX), #SHINE_SEARCH_FG130_3
    "[Great Desert Overworld] Shiny Spot near the mountain north of Asham: Item 1": Info(1222, type=Type.SHINY), #SHINE_SEARCH_FG019_1
    "[Great Desert Overworld] Shiny Spot near the mountain north of Asham: Item 2": Info(1223, type=Type.SHINY_MAX), #SHINE_SEARCH_FG019_2
    "[Great Desert Overworld] Shiny Spot near the mountain north of Asham: Item 3": Info(1224, type=Type.SHINY_MAX), #SHINE_SEARCH_FG019_3
    "[Great Desert Overworld] Shiny Spot north-west of Asham: Item 1": Info(1225, type=Type.SHINY), #SHINE_SEARCH_FG131_1
    "[Great Desert Overworld] Shiny Spot north-west of Asham: Item 2": Info(1226, type=Type.SHINY_MAX), #SHINE_SEARCH_FG131_2
    "[Great Desert Overworld] Shiny Spot north-west of Asham: Item 3": Info(1227, type=Type.SHINY_MAX), #SHINE_SEARCH_FG131_3
    "[Great Desert Overworld] Shiny Spot near Asham: Item 1": Info(1228, type=Type.SHINY), #SHINE_SEARCH_FG134_1
    "[Great Desert Overworld] Shiny Spot near Asham: Item 2": Info(1229, type=Type.SHINY_MAX), #SHINE_SEARCH_FG134_2
    "[Great Desert Overworld] Shiny Spot 1 on the coast behind the mountain west of Asham: Item 1": Info(1230, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG018_1
    "[Great Desert Overworld] Shiny Spot 1 on the coast behind the mountain west of Asham: Item 2": Info(1231, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG018_2
    "[Great Desert Overworld] Shiny Spot 1 on the coast behind the mountain west of Asham: Item 3": Info(1232, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG018_3
    "[Great Desert Overworld] Shiny Spot 2 on the coast behind the mountain west of Asham: Item 1": Info(1233, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG176_1
    "[Great Desert Overworld] Shiny Spot 2 on the coast behind the mountain west of Asham: Item 2": Info(1234, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG176_2
    "[Great Desert Overworld] Shiny Spot south of Asham: Item 1": Info(1235, type=Type.SHINY), #SHINE_SEARCH_FG132_1
    "[Great Desert Overworld] Shiny Spot south of Asham: Item 2": Info(1236, type=Type.SHINY_MAX), #SHINE_SEARCH_FG132_2
    "[Great Desert Overworld] Shiny Spot south of Asham: Item 3": Info(1237, type=Type.SHINY_MAX), #SHINE_SEARCH_FG132_3
    "[Great Desert Overworld] Shiny Spot south of the forest south of Asham: Item 1": Info(1238, type=Type.SHINY), #SHINE_SEARCH_FG133_1
    "[Great Desert Overworld] Shiny Spot south of the forest south of Asham: Item 2": Info(1239, type=Type.SHINY_MAX), #SHINE_SEARCH_FG133_2
    "[Great Desert Overworld] Shiny Spot south of the forest south of Asham: Item 3": Info(1240, type=Type.SHINY_MAX), #SHINE_SEARCH_FG133_3
    "[Great Desert Overworld] Shiny Spot west of the forest south of Asham: Item 1": Info(1241, type=Type.SHINY), #SHINE_SEARCH_FG021_1
    "[Great Desert Overworld] Shiny Spot west of the forest south of Asham: Item 2": Info(1242, type=Type.SHINY_MAX), #SHINE_SEARCH_FG021_2
    "[Great Desert Overworld] Shiny Spot in the center of the forest south of Asham: Item 1": Info(1243, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG020_1
    "[Great Desert Overworld] Shiny Spot in the center of the forest south of Asham: Item 2": Info(1244, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG020_2
    "[Great Desert Overworld] Shiny Spot in the center of the forest south of Asham: Item 3": Info(1245, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG020_3
    "[Great Desert Overworld] Shiny Spot in the forest on the coast north-east of the Pyramid: Item 1": Info(1246, type=Type.SHINY), #SHINE_SEARCH_FG137_1
    "[Great Desert Overworld] Shiny Spot in the forest on the coast north-east of the Pyramid: Item 2": Info(1247, type=Type.SHINY_MAX), #SHINE_SEARCH_FG137_2
    "[Great Desert Overworld] Shiny Spot in the forest on the coast north-east of the Pyramid: Item 3": Info(1248, type=Type.SHINY_MAX), #SHINE_SEARCH_FG137_3
    "[Great Desert Overworld] Shiny Spot north of the Pyramid: Item 1": Info(1249, type=Type.SHINY), #SHINE_SEARCH_FG138_1
    "[Great Desert Overworld] Shiny Spot north of the Pyramid: Item 2": Info(1250, type=Type.SHINY_MAX), #SHINE_SEARCH_FG138_2
    "[Great Desert Overworld] Shiny Spot north of the Pyramid: Item 3": Info(1251, type=Type.SHINY_MAX), #SHINE_SEARCH_FG138_3
    "[Great Desert Overworld] Shiny Spot north-west of Ibis: Item 1": Info(1252, type=Type.SHINY), #SHINE_SEARCH_FG139_1
    "[Great Desert Overworld] Shiny Spot north-west of Ibis: Item 2": Info(1253, type=Type.SHINY_MAX), #SHINE_SEARCH_FG139_2
    "[Great Desert Overworld] Shiny Spot north-west of Ibis: Item 3": Info(1254, type=Type.SHINY_MAX), #SHINE_SEARCH_FG139_3
    "[Great Desert Overworld] Shiny Spot 1 in the center of the desert north of Ibis: Item 1": Info(1255, type=Type.SHINY), #SHINE_SEARCH_FG142_1
    "[Great Desert Overworld] Shiny Spot 1 in the center of the desert north of Ibis: Item 2": Info(1256, type=Type.SHINY_MAX), #SHINE_SEARCH_FG142_2
    "[Great Desert Overworld] Shiny Spot 1 in the center of the desert north of Ibis: Item 3": Info(1257, type=Type.SHINY_MAX), #SHINE_SEARCH_FG142_3
    "[Great Desert Overworld] Shiny Spot 2 in the center of the desert north of Ibis: Item 1": Info(1258, type=Type.SHINY), #SHINE_SEARCH_FG140_1
    "[Great Desert Overworld] Shiny Spot 2 in the center of the desert north of Ibis: Item 2": Info(1259, type=Type.SHINY_MAX), #SHINE_SEARCH_FG140_2
    "[Great Desert Overworld] Shiny Spot 3 in the center of the desert north of Ibis: Item 1": Info(1260, type=Type.SHINY), #SHINE_SEARCH_FG141_1
    "[Great Desert Overworld] Shiny Spot north-east of Ibis: Item 1": Info(1261, type=Type.SHINY), #SHINE_SEARCH_FG022_1
    "[Great Desert Overworld] Shiny Spot north-east of Ibis: Item 2": Info(1262, type=Type.SHINY_MAX), #SHINE_SEARCH_FG022_2
    "[Great Desert Overworld] Shiny Spot north-east of Ibis: Item 3": Info(1263, type=Type.SHINY_MAX), #SHINE_SEARCH_FG022_3
    "[Great Desert Overworld] Shiny Spot in the rocky area north-east of Ibis: Item 1": Info(1264, type=Type.SHINY), #SHINE_SEARCH_FG136_1
    "[Great Desert Overworld] Shiny Spot in the rocky area north-east of Ibis: Item 2": Info(1265, type=Type.SHINY_MAX), #SHINE_SEARCH_FG136_2
    "[Great Desert Overworld] Shiny Spot in the mountain east of Ibis: Item 1": Info(1266, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG023_1
    "[Great Desert Overworld] Shiny Spot in the mountain east of Ibis: Item 2": Info(1267, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG023_2
    "[Great Desert Overworld] Shiny Spot near Desert Shrine: Item 1": Info(1268, type=Type.SHINY), #SHINE_SEARCH_FG135_1
    "[Great Desert Overworld] Shiny Spot near Desert Shrine: Item 2": Info(1269, type=Type.SHINY_MAX), #SHINE_SEARCH_FG135_2
    "[Great Desert Overworld] Shiny Spot near Desert Shrine: Item 3": Info(1270, type=Type.SHINY_MAX), #SHINE_SEARCH_FG135_3
    # ----- Portoga Overworld -----
    # 040 041 210 042
    "[Portoga Overworld] Shiny Spot in the forest west of the path to Portoga: Item 1": Info(1271, type=Type.SHINY), #SHINE_SEARCH_FG143_1
    "[Portoga Overworld] Shiny Spot in the forest west of the path to Portoga: Item 2": Info(1272, type=Type.SHINY_MAX), #SHINE_SEARCH_FG143_2
    "[Portoga Overworld] Shiny Spot north of Portoga: Item 1": Info(1273, type=Type.SHINY), #SHINE_SEARCH_FG145_1
    "[Portoga Overworld] Shiny Spot north of Portoga: Item 2": Info(1274, type=Type.SHINY_MAX), #SHINE_SEARCH_FG145_2
    "[Portoga Overworld] Shiny Spot north of Portoga: Item 3": Info(1275, type=Type.SHINY_MAX), #SHINE_SEARCH_FG145_3
    "[Portoga Overworld] Shiny Spot in the mountain north-west of Portoga: Item 1": Info(1276, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG012_1
    "[Portoga Overworld] Shiny Spot in the mountain north-west of Portoga: Item 2": Info(1277, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG012_2
    "[Portoga Overworld] Shiny Spot in the mountain north-west of Portoga: Item 3": Info(1278, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG012_3
    "[Portoga Overworld] Shiny Spot west of Portoga: Item 1": Info(1279, type=Type.SHINY), #SHINE_SEARCH_FG144_1
    "[Portoga Overworld] Shiny Spot west of Portoga: Item 2": Info(1280, type=Type.SHINY_MAX), #SHINE_SEARCH_FG144_2
    # ----- Central Overworld -----
    # 045 046 044 043 047 217 048 086 049 050 218 051 089 052 053 054 055 056 057 058 059 219 090 091 092
    # 093 060 061 062 095 232 220 063 097 101 106 107 105 104 103 102 221 110 108 222 117 215 115 116 114 113(2)
    "[Central Overworld] Shiny Spot south-west of Olivia's Promontory: Item 1": Info(1281, type=Type.SHINY), #SHINE_SEARCH_FG033_1
    "[Central Overworld] Shiny Spot south-west of Olivia's Promontory: Item 2": Info(1282, type=Type.SHINY_MAX), #SHINE_SEARCH_FG033_2
    "[Central Overworld] Shiny Spot south-west of Olivia's Promontory: Item 3": Info(1283, type=Type.SHINY_MAX), #SHINE_SEARCH_FG033_3
    "[Central Overworld] Shiny Spot south-east of Olivia's Promontory: Item 1": Info(1284, type=Type.SHINY), #SHINE_SEARCH_FG146_1
    "[Central Overworld] Shiny Spot south-east of Olivia's Promontory: Item 2": Info(1285, type=Type.SHINY_MAX), #SHINE_SEARCH_FG146_2
    "[Central Overworld] Shiny Spot south-east of Olivia's Promontory: Item 3": Info(1286, type=Type.SHINY_MAX), #SHINE_SEARCH_FG146_3
    "[Central Overworld] Shiny Spot north of Nordy's Grotto's right entrance: Item 1": Info(1287, type=Type.SHINY), #SHINE_SEARCH_FG149_1
    "[Central Overworld] Shiny Spot north of Nordy's Grotto's right entrance: Item 2": Info(1288, type=Type.SHINY_MAX), #SHINE_SEARCH_FG149_2
    "[Central Overworld] Shiny Spot north of Nordy's Grotto's right entrance: Item 3": Info(1289, type=Type.SHINY_MAX), #SHINE_SEARCH_FG149_3
    "[Central Overworld] Shiny Spot east of Nordy's Grotto's right entrance: Item 1": Info(1290, type=Type.SHINY), #SHINE_SEARCH_FG034_1
    "[Central Overworld] Shiny Spot east of Nordy's Grotto's right entrance: Item 2": Info(1291, type=Type.SHINY_MAX), #SHINE_SEARCH_FG034_2
    "[Central Overworld] Shiny Spot near the lake south of Nordy's Grotto's right entrance: Item 1": Info(1292, type=Type.SHINY), #SHINE_SEARCH_FG035_1
    "[Central Overworld] Shiny Spot near the lake south of Nordy's Grotto's right entrance: Item 2": Info(1293, type=Type.SHINY_MAX), #SHINE_SEARCH_FG035_2
    "[Central Overworld] Shiny Spot near the lake south of Nordy's Grotto's right entrance: Item 3": Info(1294, type=Type.SHINY_MAX), #SHINE_SEARCH_FG035_3
    "[Central Overworld] Shiny Spot in the mountain north-west of Baharata: Item 1": Info(1295, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG037_1
    "[Central Overworld] Shiny Spot in the mountain north-west of Baharata: Item 2": Info(1296, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG037_2
    "[Central Overworld] Shiny Spot in the mountain north-west of Baharata: Item 3": Info(1297, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG037_3
    "[Central Overworld] Shiny Spot west of the mountain north-west of Baharata: Item 1": Info(1298, type=Type.SHINY), #SHINE_SEARCH_FG147_1
    "[Central Overworld] Shiny Spot west of the mountain north-west of Baharata: Item 2": Info(1299, type=Type.SHINY_MAX), #SHINE_SEARCH_FG147_2
    "[Central Overworld] Shiny Spot on the small coast west of the mountain north-west of Baharata: Item 1": Info(1300, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG036_1
    "[Central Overworld] Shiny Spot on the small coast west of the mountain north-west of Baharata: Item 2": Info(1301, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG036_2
    "[Central Overworld] Shiny Spot on the small coast west of the mountain north-west of Baharata: Item 3": Info(1302, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG036_3
    "[Central Overworld] Shiny Spot in the desert area west of the lake north-west of Baharata: Item 1": Info(1303, type=Type.SHINY), #SHINE_SEARCH_FG148_1
    "[Central Overworld] Shiny Spot in the desert area west of the lake north-west of Baharata: Item 2": Info(1304, type=Type.SHINY_MAX), #SHINE_SEARCH_FG148_2
    "[Central Overworld] Shiny Spot west of Baharata: Item 1": Info(1305, type=Type.SHINY), #SHINE_SEARCH_FG038_1
    "[Central Overworld] Shiny Spot west of Baharata: Item 2": Info(1306, type=Type.SHINY_MAX), #SHINE_SEARCH_FG038_2
    "[Central Overworld] Shiny Spot west of Baharata: Item 3": Info(1307, type=Type.SHINY_MAX), #SHINE_SEARCH_FG038_3
    "[Central Overworld] Shiny Spot in the mountain south-west of Baharata: Item 1": Info(1308, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG039_1
    "[Central Overworld] Shiny Spot in the mountain south-west of Baharata: Item 2": Info(1309, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG039_2
    "[Central Overworld] Shiny Spot south of the mountain south-west of Baharata: Item 1": Info(1310, type=Type.SHINY), #SHINE_SEARCH_FG150_1
    "[Central Overworld] Shiny Spot south of the mountain south-west of Baharata: Item 2": Info(1311, type=Type.SHINY_MAX), #SHINE_SEARCH_FG150_2
    "[Central Overworld] Shiny Spot on the small island south of Baharata: Item 1": Info(1312, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG215_1
    "[Central Overworld] Shiny Spot on the small island south of Baharata: Item 2": Info(1313, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG215_2
    "[Central Overworld] Shiny Spot on the small island south of Baharata: Item 3": Info(1314, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG215_3
    "[Central Overworld] Shiny Spot east of Baharata: Item 1": Info(1315, type=Type.SHINY), #SHINE_SEARCH_FG152_1
    "[Central Overworld] Shiny Spot east of Baharata: Item 2": Info(1316, type=Type.SHINY_MAX), #SHINE_SEARCH_FG152_2
    "[Central Overworld] Shiny Spot east of Baharata: Item 3": Info(1317, type=Type.SHINY_MAX), #SHINE_SEARCH_FG152_3
    "[Central Overworld] Shiny Spot on the bottom edge coast south-east of Baharata: Item 1": Info(1318, type=Type.SHINY), #SHINE_SEARCH_FG151_1
    "[Central Overworld] Shiny Spot on the bottom edge coast south-east of Baharata: Item 2": Info(1319, type=Type.SHINY_MAX), #SHINE_SEARCH_FG151_2
    "[Central Overworld] Shiny Spot on the bottom edge coast south-east of Baharata: Item 3": Info(1320, type=Type.SHINY_MAX), #SHINE_SEARCH_FG151_3
    "[Central Overworld] Shiny Spot on the coast near Jipang to the east of Baharata: Item 1": Info(1321, type=Type.SHINY), #SHINE_SEARCH_FG041_1
    "[Central Overworld] Shiny Spot on the coast near Jipang to the east of Baharata: Item 2": Info(1322, type=Type.SHINY_MAX), #SHINE_SEARCH_FG041_2
    "[Central Overworld] Shiny Spot on the coast near Jipang to the east of Baharata: Item 3": Info(1323, type=Type.SHINY_MAX), #SHINE_SEARCH_FG041_3
    "[Central Overworld] Shiny Spot north-east of Kidnapper's Cave: Item 1": Info(1324, type=Type.SHINY), #SHINE_SEARCH_FG157_1
    "[Central Overworld] Shiny Spot north-east of Kidnapper's Cave: Item 2": Info(1325, type=Type.SHINY_MAX), #SHINE_SEARCH_FG157_2
    "[Central Overworld] Shiny Spot south of Alltrades Abbey: Item 1": Info(1326, type=Type.SHINY), #SHINE_SEARCH_FG160_1
    "[Central Overworld] Shiny Spot south of Alltrades Abbey: Item 2": Info(1327, type=Type.SHINY_MAX), #SHINE_SEARCH_FG160_2
    "[Central Overworld] Shiny Spot south of Alltrades Abbey: Item 3": Info(1328, type=Type.SHINY_MAX), #SHINE_SEARCH_FG160_3
    "[Central Overworld] Shiny Spot north of Alltrades Abbey: Item 1": Info(1329, type=Type.SHINY), #SHINE_SEARCH_FG040_1
    "[Central Overworld] Shiny Spot north of Alltrades Abbey: Item 2": Info(1330, type=Type.SHINY_MAX), #SHINE_SEARCH_FG040_2
    "[Central Overworld] Shiny Spot north of Alltrades Abbey: Item 3": Info(1331, type=Type.SHINY_MAX), #SHINE_SEARCH_FG040_3
    "[Central Overworld] Shiny Spot south-east of Alltrades Abbey: Item 1": Info(1332, type=Type.SHINY), #SHINE_SEARCH_FG158_1
    "[Central Overworld] Shiny Spot south-east of Alltrades Abbey: Item 2": Info(1333, type=Type.SHINY_MAX), #SHINE_SEARCH_FG158_2
    "[Central Overworld] Shiny Spot south-east of Alltrades Abbey: Item 3": Info(1334, type=Type.SHINY_MAX), #SHINE_SEARCH_FG158_3
    "[Central Overworld] Shiny Spot near the coast south-west of Wayfarer's Inn: Item 1": Info(1335, type=Type.SHINY), #SHINE_SEARCH_FG042_1
    "[Central Overworld] Shiny Spot near the coast south-west of Wayfarer's Inn: Item 2": Info(1336, type=Type.SHINY_MAX), #SHINE_SEARCH_FG042_2
    "[Central Overworld] Shiny Spot near the coast south-west of Wayfarer's Inn: Item 3": Info(1337, type=Type.SHINY_MAX), #SHINE_SEARCH_FG042_3
    "[Central Overworld] Shiny Spot on the other side of the lake north-west of Wayfarer's Inn: Item 1": Info(1338, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG043_1
    "[Central Overworld] Shiny Spot on the other side of the lake north-west of Wayfarer's Inn: Item 2": Info(1339, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG043_2
    "[Central Overworld] Shiny Spot on the small island west of Jipang: Item 1": Info(1340, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG169_1
    "[Central Overworld] Shiny Spot on the small island west of Jipang: Item 2": Info(1341, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG169_2
    "[Central Overworld] Shiny Spot on the small island south-west of Jipang: Item 1": Info(1342, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG170_1
    "[Central Overworld] Shiny Spot on the small island south-west of Jipang: Item 2": Info(1343, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG170_2
    "[Central Overworld] Shiny Spot on the small island south-west of Jipang: Item 3": Info(1344, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG170_3
    "[Central Overworld] Shiny Spot on the first small island north of Orochi's Lair: Item 1": Info(1345, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG171_1
    "[Central Overworld] Shiny Spot on the first small island north of Orochi's Lair: Item 2": Info(1346, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG171_2
    "[Central Overworld] Shiny Spot on the first small island north of Orochi's Lair: Item 3": Info(1347, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG171_3
    "[Central Overworld] Shiny Spot on the second small island north of Orochi's Lair: Item 1": Info(1348, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG172_1
    "[Central Overworld] Shiny Spot on the second small island north of Orochi's Lair: Item 2": Info(1349, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG172_2
    "[Central Overworld] Shiny Spot on the second small island north of Orochi's Lair: Item 3": Info(1350, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG172_3
    "[Central Overworld] Shiny Spot near the coast north-east of Wayfarer's Inn: Item 1": Info(1351, type=Type.SHINY), #SHINE_SEARCH_FG044_1
    "[Central Overworld] Shiny Spot near the coast north-east of Wayfarer's Inn: Item 2": Info(1352, type=Type.SHINY_MAX), #SHINE_SEARCH_FG044_2
    "[Central Overworld] Shiny Spot near the coast north-east of Wayfarer's Inn: Item 3": Info(1353, type=Type.SHINY_MAX), #SHINE_SEARCH_FG044_3
    "[Central Overworld] Shiny Spot north of Wayfarer's Inn: Item 1": Info(1354, type=Type.SHINY), #SHINE_SEARCH_FG153_1
    "[Central Overworld] Shiny Spot north of Wayfarer's Inn: Item 2": Info(1355, type=Type.SHINY_MAX), #SHINE_SEARCH_FG153_2
    "[Central Overworld] Shiny Spot north of Wayfarer's Inn: Item 3": Info(1356, type=Type.SHINY_MAX), #SHINE_SEARCH_FG153_3
    "[Central Overworld] Shiny Spot near the lake south-west of Mur: Item 1": Info(1357, type=Type.SHINY), #SHINE_SEARCH_FG154_1
    "[Central Overworld] Shiny Spot near the lake south-west of Mur: Item 2": Info(1358, type=Type.SHINY_MAX), #SHINE_SEARCH_FG154_2
    "[Central Overworld] Shiny Spot near the lake south-west of Mur: Item 3": Info(1359, type=Type.SHINY_MAX), #SHINE_SEARCH_FG154_3
    "[Central Overworld] Shiny Spot on the small coast south of Mur: Item 1": Info(1360, type=Type.SHINY), #SHINE_SEARCH_FG045_1
    "[Central Overworld] Shiny Spot on the small coast south of Mur: Item 2": Info(1361, type=Type.SHINY_MAX), #SHINE_SEARCH_FG045_2
    "[Central Overworld] Shiny Spot on the small coast south of Mur: Item 3": Info(1362, type=Type.SHINY_MAX), #SHINE_SEARCH_FG045_3
    "[Central Overworld] Shiny Spot north-west of Mur: Item 1": Info(1363, type=Type.SHINY), #SHINE_SEARCH_FG155_1
    "[Central Overworld] Shiny Spot north-west of Mur: Item 2": Info(1364, type=Type.SHINY_MAX), #SHINE_SEARCH_FG155_2
    "[Central Overworld] Shiny Spot in the mountain north of Mur: Item 1": Info(1365, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG046_1
    "[Central Overworld] Shiny Spot in the mountain north of Mur: Item 2": Info(1366, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG046_2
    "[Central Overworld] Shiny Spot near the top edge coast north-west of Mur: Item 1": Info(1367, type=Type.SHINY), #SHINE_SEARCH_FG156_1
    "[Central Overworld] Shiny Spot near the top edge coast north-west of Mur: Item 2": Info(1368, type=Type.SHINY_MAX), #SHINE_SEARCH_FG156_2
    "[Central Overworld] Shiny Spot near the top edge coast north-west of Mur: Item 3": Info(1369, type=Type.SHINY_MAX), #SHINE_SEARCH_FG156_3
    "[Central Overworld] Shiny Spot on the other side of the river west of Mur: Item 1": Info(1370, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG047_1
    "[Central Overworld] Shiny Spot on the other side of the river west of Mur: Item 2": Info(1371, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG047_2
    "[Central Overworld] Shiny Spot on the other side of the river west of Mur: Item 3": Info(1372, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG047_3
    "[Central Overworld] Shiny Spot on the other side of the river north-west of Mur: Item 1": Info(1373, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG218_1
    "[Central Overworld] Shiny Spot on the other side of the river north-west of Mur: Item 2": Info(1374, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG218_2
    "[Central Overworld] Shiny Spot on the other side of the river north-west of Mur: Item 3": Info(1375, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG218_3
    "[Central Overworld] Shiny Spot 1 south of Shrine of the Dwarf: Item 1": Info(1376, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG050_1
    "[Central Overworld] Shiny Spot 1 south of Shrine of the Dwarf: Item 2": Info(1377, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG050_2
    "[Central Overworld] Shiny Spot 1 south of Shrine of the Dwarf: Item 3": Info(1378, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG050_3
    "[Central Overworld] Shiny Spot 2 south of Shrine of the Dwarf: Item 1": Info(1379, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG222_1
    "[Central Overworld] Shiny Spot 2 south of Shrine of the Dwarf: Item 2": Info(1380, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG222_2
    "[Central Overworld] Shiny Spot 2 south of Shrine of the Dwarf: Item 3": Info(1381, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG222_3
    "[Central Overworld] Shiny Spot 3 south of Shrine of the Dwarf: Item 1": Info(1382, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG221_1
    "[Central Overworld] Shiny Spot 3 south of Shrine of the Dwarf: Item 2": Info(1383, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG221_2
    "[Central Overworld] Shiny Spot 1 east of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1384, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG220_1
    "[Central Overworld] Shiny Spot 1 east of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1385, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG220_2
    "[Central Overworld] Shiny Spot 2 east of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1386, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG219_1
    "[Central Overworld] Shiny Spot 2 east of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1387, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG219_2
    "[Central Overworld] Shiny Spot 2 east of the center of the forest south of Shrine of the Dwarf: Item 3": Info(1388, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG219_3
    "[Central Overworld] Shiny Spot south-east of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1389, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG048_1
    "[Central Overworld] Shiny Spot south-east of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1390, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG048_2
    "[Central Overworld] Shiny Spot south of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1391, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG049_1
    "[Central Overworld] Shiny Spot south of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1392, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG049_2
    "[Central Overworld] Shiny Spot south of the center of the forest south of Shrine of the Dwarf: Item 3": Info(1393, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG049_3
    "[Central Overworld] Shiny Spot on the small coast south-west of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1394, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG224_1
    "[Central Overworld] Shiny Spot on the small coast south-west of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1395, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG224_2
    "[Central Overworld] Shiny Spot 1 north-west of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1396, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG223_1
    "[Central Overworld] Shiny Spot 1 north-west of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1397, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG223_2
    "[Central Overworld] Shiny Spot 2 north-west of the center of the forest south of Shrine of the Dwarf: Item 1": Info(1398, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG051_1
    "[Central Overworld] Shiny Spot 2 north-west of the center of the forest south of Shrine of the Dwarf: Item 2": Info(1399, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG051_2
    "[Central Overworld] Shiny Spot 2 north-west of the center of the forest south of Shrine of the Dwarf: Item 3": Info(1400, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG051_3
    "[Central Overworld] Shiny Spot north-west of Olivia's Promontory: Item 1": Info(1401, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG052_1
    "[Central Overworld] Shiny Spot north-west of Olivia's Promontory: Item 2": Info(1402, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG052_2
    "[Central Overworld] Shiny Spot north-west of Olivia's Promontory: Item 3": Info(1403, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG052_3
    "[Central Overworld] Shiny Spot in the mountain north of Olivia's Promontory: Item 1": Info(1404, rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG053_1
    "[Central Overworld] Shiny Spot in the mountain north of Olivia's Promontory: Item 2": Info(1405, rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG053_2
    "[Central Overworld] Shiny Spot south-west of Castle of the Dragon Queen: Item 1": Info(1406, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG213_1
    "[Central Overworld] Shiny Spot south-west of Castle of the Dragon Queen: Item 2": Info(1407, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG213_2
    "[Central Overworld] Shiny Spot north-west of Castle of the Dragon Queen: Item 1": Info(1408, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG054_1
    "[Central Overworld] Shiny Spot north-west of Castle of the Dragon Queen: Item 2": Info(1409, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG054_2
    "[Central Overworld] Shiny Spot north-east of Castle of the Dragon Queen: Item 1": Info(1410, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG055_1
    "[Central Overworld] Shiny Spot north-east of Castle of the Dragon Queen: Item 2": Info(1411, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG055_2
    "[Central Overworld] Shiny Spot north-east of Castle of the Dragon Queen: Item 3": Info(1412, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG055_3
    "[Central Overworld] Shiny Spot 1 on the small coast north of Castle of the Dragon Queen: Item 1": Info(1413, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG214_1
    "[Central Overworld] Shiny Spot 1 on the small coast north of Castle of the Dragon Queen: Item 2": Info(1414, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG214_2
    "[Central Overworld] Shiny Spot 1 on the small coast north of Castle of the Dragon Queen: Item 3": Info(1415, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG214_3
    "[Central Overworld] Shiny Spot 2 on the small coast north of Castle of the Dragon Queen: Item 1": Info(1416, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG056_1
    "[Central Overworld] Shiny Spot 2 on the small coast north of Castle of the Dragon Queen: Item 2": Info(1417, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG056_2
    "[Central Overworld] Shiny Spot 2 on the small coast north of Castle of the Dragon Queen: Item 3": Info(1418, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG056_3
    # ----- Eastern Overworld -----
    # 173 174
    "[Eastern Overworld] Shiny Spot d: Item 1": Info(1419, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY), #SHINE_SEARCH_FG210_1
    "[Eastern Overworld] Shiny Spot d: Item 2": Info(1420, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG210_2
    "[Eastern Overworld] Shiny Spot d: Item 3": Info(1421, rules.HAS_SHIP | rules.HAS_BIRD, type=Type.SHINY_MAX), #SHINE_SEARCH_FG210_3
    # ----- Southern Mountains Overworld -----
    # 
    # ----- Manoza Overworld -----
    # 
    # ----- Ocean Overworld -----
    # 
    # ----- Alefgard Overworld -----
    # 
}