#include "WorldData.h"

std::unordered_map<int, std::string> WorldData::rev_locations = {};

const std::unordered_map<std::string, int> WorldData::locations =
{
    // ----- Aliahan -----
    {"SEARCH_Aliahan_Out_BARREL_0", 1},
    {"SEARCH_Aliahan_Out_BARREL_1", 2},
    {"SEARCH_Aliahan_Out_POT_0", 3},
    {"SEARCH_Aliahan_Out_POT_1", 4},
    {"SEARCH_Aliahan_Out_GROUND_0", 5},
    {"SEARCH_Aliahan_Out_GROUND_1", 6},
    {"SEARCH_Aliahan_Out_GROUND_2", 7},
    {"SEARCH_Aliahan_Out_GROUND_3", 8},
    {"SEARCH_Aliahan_Out_TREASURE_NORMAL_0", 9},
    {"SEARCH_Aliahan_House1_1F_BARREL_0", 10},
    {"SEARCH_Aliahan_House1_2F_DRAWER_0", 11},
    {"SEARCH_Aliahan_House1_2F_DRAWER_1", 12},
    {"SEARCH_Aliahan_House2_1F_POT_0", 13},
    {"SEARCH_Aliahan_House2_2F_DRAWER_0", 14},
    //{"SEARCH_Aliahan_House3_1F_BOOKSHELF_0", 15},
    {"SEARCH_Aliahan_Inn_1F_SACK_0", 16},
    {"SEARCH_Aliahan_Inn_2F_SACK_0", 17},
    {"SEARCH_Aliahan_Inn_2F_STORAGE_0", 18},
    {"SEARCH_Aliahan_Inn_2F_POT_0", 19},
    {"SEARCH_Aliahan_Inn_2F_POT_1", 20},
    {"SEARCH_Aliahan_Luida_1F_BARREL_0", 21},
    {"SEARCH_Aliahan_Luida_2F_POT_0", 22},
    // ----- Aliahan Castle -----
    {"SEARCH_Aliahan_Castle_1F_BARREL_0", 23},
    {"SEARCH_Aliahan_Castle_1F_BARREL_1", 24},
    {"SEARCH_Aliahan_Castle_1F_BARREL_2", 25},
    {"SEARCH_Aliahan_Castle_1F_BARREL_3", 26},
    {"SEARCH_Aliahan_Castle_1F_TREASURE_NORMAL_0", 27},
    {"SEARCH_Aliahan_Castle_1F_TREASURE_NORMAL_1", 28},
    {"SEARCH_Aliahan_Castle_1F_TREASURE_NORMAL_2", 29},
    {"SEARCH_Aliahan_Castle_1F_TREASURE_NORMAL_3", 30},
    {"SEARCH_Aliahan_Castle_1F_TREASURE_NORMAL_4", 31},
    {"SEARCH_Aliahan_Castle_1F_TREASURE_NORMAL_5", 32},
    {"SEARCH_Aliahan_Castle_1F_POT_0", 33},
    {"SEARCH_Aliahan_Castle_1F_POT_1", 34},
    {"SEARCH_Aliahan_Castle_1F_GROUND_0", 35},
    {"SEARCH_Aliahan_Castle_1F_GROUND_1", 36},
    {"SEARCH_Aliahan_Castle_1FA_DRAWER_0", 37},
    {"SEARCH_Aliahan_Castle_1FB_BARREL_0", 38},
    {"SEARCH_Aliahan_Castle_1FB_POT_0", 39},
    {"SEARCH_Aliahan_Castle_2F_STORAGE_0", 40},
    {"SEARCH_Aliahan_Castle_2F_GROUND_0", 41},
    {"SEARCH_Aliahan_Castle_B1F_POT_0", 42},
    {"SEARCH_Aliahan_Castle_B1F_POT_1", 43},
    {"SEARCH_Aliahan_Castle_B1F_BARREL_0", 44},
    {"SEARCH_Aliahan_Castle_B1FB_POT_0", 45},
    {"SEARCH_Aliahan_Castle_1F_Out_BARREL_0", 46},
    // ----- Reeve -----
    {"SEARCH_Reeve_Out_GROUND_0", 47},
    {"SEARCH_Reeve_Out_GROUND_1", 48},
    {"SEARCH_Reeve_Out_BARREL_0", 49},
    {"SEARCH_Reeve_Out_BARREL_1", 50},
    {"SEARCH_Reeve_Out_POT_0", 51},
    {"SEARCH_Reeve_House1_1F_BOOKSHELF_0", 52},
    {"SEARCH_Reeve_House2_1F_POT_0", 53},
    //{"SEARCH_Reeve_House2_1F_EVENT_0", 54},
    {"SEARCH_Reeve_House2_2F_DRAWER_0", 55},
    {"SEARCH_Reeve_Church_1F_POT_0", 56},
    {"SEARCH_Reeve_Inn_1F_POT_0", 57},
    {"SEARCH_Reeve_Inn_2F_POT_0", 58},
    {"Reeve_House2_1F_SUB_0_ACTOR_0110_010", 59},
    // ----- Shrine of the Plains -----
    {"SEARCH_ReeveSouth_BARREL_0", 60},
    {"SEARCH_ReeveSouth_POT_0", 61},
    // ----- Promontory Passage -----
    {"SEARCH_MisakiCave_B2F_TREASURE_NORMAL_0", 62},
    {"SEARCH_MisakiCave_B2F_TREASURE_NORMAL_1", 63},
    {"SEARCH_MisakiCave_B2F_TREASURE_NORMAL_2", 64},
    {"SEARCH_MisakiCave_B2F_TREASURE_NORMAL_3", 65},
    // ----- Dreamer's Tower -----
    {"SEARCH_NajimiTower_B1F_TREASURE_NORMAL_0", 66},
    {"SEARCH_NajimiTower_B1F_TREASURE_NORMAL_1", 67},
    {"SEARCH_NajimiTower_B1F_TREASURE_NORMAL_2", 68},
    {"SEARCH_NajimiTower_1F_TREASURE_NORMAL_0", 69},
    {"SEARCH_NajimiTower_1F_POT_0", 70},
    {"SEARCH_NajimiTower_2F_TREASURE_NORMAL_0", 71},
    {"SEARCH_NajimiTower_2F_TREASURE_NORMAL_1", 72},
    {"SEARCH_NajimiTower_3F_TREASURE_NORMAL_0", 73},
    {"SEARCH_NajimiTower_3F_TREASURE_NORMAL_1", 74},
    {"SEARCH_NajimiTower_Penthouse_TREASURE_NORMAL_0", 75},
    {"SEARCH_NajimiTower_Penthouse_BOOKSHELF_0", 76},
    {"NajimiTower_Penthouse_MAIN_0_ACTOR_0110_010", 77},
    // ----- Little Shrine -----
    {"SEARCH_SmallShrine_B1F_POT_0", 78},
    {"SEARCH_SmallShrine_B1F_POT_1", 79},
    //{"SEARCH_SmallShrine_B1F_BOOKSHELF_0", 80},
    // ----- Path of Promise -----
    //{"SEARCH_IzanaiCave_B1F_After_TREASURE_IMPORTANT_0", 81},
    //{"SEARCH_IzanaiCave_B1F_After_EVENT_0", 82},
    {"SEARCH_IzanaiCave_B2F_TREASURE_NORMAL_0", 83},
    {"SEARCH_IzanaiCave_B2F_TREASURE_NORMAL_1", 84},
    {"SEARCH_IzanaiCave_B2F_TREASURE_NORMAL_2", 85},
    {"SEARCH_IzanaiCave_B2F_BARREL_0", 86},
    {"SEARCH_IzanaiCave_B2F_GROUND_0", 87},
    {"SEARCH_IzanaiCave_B3FA_TREASURE_NORMAL_0", 88},
    {"SEARCH_IzanaiCave_B3FA_POT_0", 89},
    {"SEARCH_IzanaiCave_B3FA_POT_1", 90},
    {"SEARCH_IzanaiCave_B3FB_TREASURE_NORMAL_0", 91},
    {"SEARCH_IzanaiCave_B3FB_POT_0", 92},
    {"SEARCH_IzanaiCave_B3FB_POT_1", 93},
    // ----- Shrine of Promise -----
    {"SEARCH_IzanaiShrine_1F_GROUND_0", 94},
    {"SEARCH_IzanaiShrine_1F_POT_0", 95},
};

const std::unordered_map<int, std::string> WorldData::items =
{
    // GOLD
    {2, "GOLD_31"},
    {8, "GOLD_50"},
    {12, "GOLD_12"},
    {14, "GOLD_6"},
    {17, "GOLD_9"},
    {25, "GOLD_7"},
    {28, "GOLD_26"},
    {31, "GOLD_500"},
    {34, "GOLD_210"},
    {36, "GOLD_33"},
    {41, "GOLD_76"},
    {42, "GOLD_113"},
    {49, "GOLD_143"},
    {53, "GOLD_17"},
    {55, "GOLD_32"},
    {56, "GOLD_162"},
    // USABLE ITEMS
    {1, "ITEM_USE_ITEM_HOLY_WATER"},
    {3, "ITEM_USE_ITEM_CHIMERA_WING"},
    {4, "ITEM_USE_ITEM_MEDICAL_HERB"},
    {6, "ITEM_USE_ITEM_ANTIDOTAL_HERB"},
    {10, "ITEM_USE_ITEM_MAGIC_WATER"},
    {16, "ITEM_USE_ITEM_WHISPERING_NECTAR"},
    {23, "ITEM_USE_ITEM_POUCH_OF_MUSK"},
    {32, "ITEM_USE_ITEM_STRONG_MEDICINE"},
    // USABLE ITEMS SEEDS
    {9, "ITEM_USE_ITEM_SEED_OF_STRENGTH"},
    {15, "ITEM_USE_ITEM_SEED_OF_LIFE"},
    {19, "ITEM_USE_ITEM_SEED_OF_AGILITY"},
    {24, "ITEM_USE_ITEM_SEED_OF_MAGIC"},
    {33, "ITEM_USE_ITEM_SEED_OF_PROTECTION"},
    {37, "ITEM_USE_ITEM_SEED_OF_RESILIENCE"},
    {39, "ITEM_USE_ITEM_SEED_OF_WISDOM"},
    // USABLE ITEMS BOOKS
    {38, "ITEM_USE_ITEM_DIARY_OF_A_HARDMAN"},
    {46, "ITEM_USE_ITEM_THE_GIRLS_OWN_ANNUAL"},
    // MEDAL
    {11, "ITEM_SMALL_MEDAL"},
    // WEAPONS
    {18, "ITEM_EQUIP_WEAPON_RUNE_STAFF"},
    {35, "ITEM_EQUIP_WEAPON_OAKEN_CLUB"},
    {45, "ITEM_EQUIP_WEAPON_BOOMERANG"},
    {54, "ITEM_EQUIP_WEAPON_CHAIN_SICKLE"},
    // SHIELDS
    {27, "ITEM_EQUIP_SHIELD_POT_LID"},
    {44, "ITEM_EQUIP_SHIELD_LEATHER_SHIELD"},
    // EQUIPMENT HELMETS
    {13, "ITEM_EQUIP_HELMET_LEATHER_HAT"},
    {43, "ITEM_EQUIP_HELMET_HARDWOOD_HEADWEAR"},
    // EQUIPMENT ARMORS
    {5, "ITEM_EQUIP_ARMOR_TRAINING_TOGS"},
    {29, "ITEM_EQUIP_ARMOR_WAYFARERS_CLOTHES"},
    {52, "ITEM_EQUIP_ARMOR_TORTOISE_SHELL"},
    // EQUIPMENT ACCESSORIES
    {7, "ITEM_EQUIP_ACCESSORY_DRAGON_SCALES"},
    {20, "ITEM_EQUIP_ACCESSORY_WIND_EARRINGS"},
    {21, "ITEM_EQUIP_ACCESSORY_RING_OF_REASON"},
    {22, "ITEM_EQUIP_ACCESSORY_MIGHTY_ARMLET"},
    {26, "ITEM_EQUIP_ACCESSORY_ALARM_RING"},
    {50, "ITEM_EQUIP_ACCESSORY_BUNNY_TAIL"},
    {51, "ITEM_EQUIP_ACCESSORY_COWER_RING"},
    // IMPORTANT
    {40, "ITEM_IMPORTANT_WRECKING_BALL"},
    {47, "ITEM_IMPORTANT_THIEFS_KEY"},
    {48, "ITEM_IMPORTANT_ADVENTURERS_MAP"},
};
